<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <title>Hello World! from StringTemplate</title>
</head>
<body>
<div>
  <p><span style="color:green;font-size:1.4em">Hello World! from StringTemplate</span></p><br/>
  <p>    
    Message: <span style="color:red">$message$</span>
  </p>
  <p>
    Timestamp: <span style="color:red">$timestamp$</span>
  </p>
</div>
</body>