
var Utils={isBoolean:function(_1){return typeof _1=="boolean";},isNumber:function(_2){return typeof _2=="number";},isString:function(_3){return typeof _3=="string";},isArray:function(_4){return _4&&!Utils.isString(_4)?Utils.isNumber(_4.length):false;},isNode:function(_5){return _5&&_5.nodeName;},isWidget:function(_6){return _6&&_6.getElement;},isDraggable:function(el){return el&&el.__drag;},applyStyle:function(el,_9){if(document.all&&!window.opera){el.style.setAttribute("cssText",_9);}else{el.setAttribute("style",_9);}},getCssStyle:function(el,_b){if(el.currentStyle){return el.currentStyle[_b];}else{if(window.getComputedStyle){return window.getComputedStyle(el,"").getPropertyValue(_b);}}
return null;},getStyleProperty:function(el,_d){var p=el.style[_d];return p?p:Utils.getCssStyle(el,_d);},getZIndex:function(el){return el.style.zIndex?el.style.zIndex:(document.all?Utils.getCssStyle(el,"zIndex"):Utils.getCssStyle(el,"z-index"));},refreshElement:function(el){while(el.hasChildNodes()){el.removeChild(el.firstChild);}},trim:function(str){return str.replace(/^\s+/g,"").replace(/\s+$/g,"");},trimLineBreaks:function(str){return str.replace(/(\r\n|[\r\n])/g," ");},stopEvent:function(ev){if(!ev){ev=window.event;}
if(ev.stopPropagation){ev.stopPropagation();}else{ev.cancelBubble=true;}
if(ev.preventDefault){ev.preventDefault();}else{ev.returnValue=false;}},getName:function(el){return el.name?el.name:el.getAttribute("name");},getParentName:function(el){var p=el.parentNode;if(!p){return null;}
var _17=p.name?p.name:p.getAttribute("name");return _17?_17:Utils.getParentName(p);},addHandlerToEvent:function(_18,el,ev){if(el.addEventListener){el.addEventListener(ev.substring(2),_18,false);}else{if(el.attachEvent){el.attachEvent(ev,_18);}else{var _1b=el[ev];el[ev]=function(e){_1b(e);_18(e);};}}},addOnLoad:function(_1d){var _1e=window.onload;window.onload=function(){if(typeof _1e=="function"){_1e();}
_1d();};},addOnUnload:function(_1f){var _20=window.onunload;window.onunload=function(){if(typeof _20=="function"){_20();}
_1f();};},getEventSource:function(ev){if(!ev){ev=window.event;}
return ev.target?ev.target:ev.srcElement;},toggle:function(el){if(!el.style.display||el.style.display!="none"){el.style.display="none";}else{el.style.display="block";}},hideFirstChild:function(_23){if(_23&&_23.firstChild){_23.firstChild.style.display="none";}},hideLastChild:function(_24){if(_24&&_24.lastChild){_24.lastChild.style.display="none";}},getEventCoords:function(ev){var x=0;var y=0;if(document.all){x=document.documentElement.scrollLeft||document.body.scrollLeft;y=document.documentElement.scrollTop||document.body.scrollTop;x+=window.event.clientX;y+=window.event.clientY;}else{x=ev.pageX;y=ev.pageY;}
return{x:x,y:y};},getLeft:function(el){var _29=0;for(;;){if(!el.offsetParent){_29+=el.offsetLeft;break;}
_29+=(el.offsetLeft-el.scrollLeft);el=el.offsetParent;}
return _29;},getTop:function(el){var top=0;for(;;){if(!el.offsetParent){top+=el.offsetTop;break;}
top+=(el.offsetTop-el.scrollTop);el=el.offsetParent;}
return top;},getCoords:function(el){var _2d=0;var top=0;for(;;){if(!el.offsetParent){_2d+=el.offsetLeft;top+=el.offsetTop;break;}
_2d+=(el.offsetLeft-el.scrollLeft);top+=(el.offsetTop-el.scrollTop);el=el.offsetParent;}
return{x:_2d,y:top};},getCenterCoords:function(){var _2f=document.documentElement.scrollLeft||document.body.scrollLeft;var _30=document.documentElement.scrollTop||document.body.scrollTop;var _31=document.body.clientWidth/2+_2f;var top=document.body.clientHeight/2+_30;return{x:_31,y:top};},positionCenter:function(el){var _34=(document.body.clientWidth-el.offsetWidth)/2;var top=(document.body.clientHeight-el.offsetHeight)/2;var _36=document.documentElement.scrollLeft||document.body.scrollLeft;var _37=document.documentElement.scrollTop||document.body.scrollTop;el.style.left=[_36+_34,"px"].join("");el.style.top=[_37+top,"px"].join("");},newXHR:function(){return window.XMLHttpRequest?new XMLHttpRequest():new ActiveXObject("Microsoft.XMLHTTP");},_script_counter:0,findParentByNodeName:function(el,_39){return el.nodeName==_39?el:el.parentNode?Utils.findParentByNodeName(el.parentNode,_39):null;},deleteCookie:function(_3a){document.cookie=[_3a,"=","; expires=Thu, 01-Jan-70 00:00:01 GMT"].join("");},getCookie:function(_3b){var c=document.cookie.split(";");for(var i=0;i<c.length;i++){var t=Utils.trim(c[i]);if(t.substring(0,_3b.length)==_3b){return t.substring(_3b.length+1,t.length);}}
return null;},createCookie:function(_3f,_40,_41){var _42=Utils.isNumber(_41)?new Date((1000*_41)+new Date().getTime()).toGMTString():"";document.cookie=[_3f,"=",_40,"; expires=",_42].join("");},validateForm:function(_43,_44,_45){if(_45){return Utils.validateFormResolveName(_43,_44);}
for(var i=0;i<_43.elements.length;i++){var _47=_43.elements[i];if("true"!=_47.getAttribute("required")){continue;}
if(_47.type.toLowerCase()=="text"){_47.value=Utils.trim(_47.value);if(_47.value.length<1){var _48=Utils.getName(_47);var msg=["Required field: ",_48.substring(0,1).toUpperCase(),_48.substring(1)].join("");if(Utils.isNode(_44)){_44.innerHTML=msg;}else{alert(msg);}
_47.focus();return false;}}else{if(_47.type.toLowerCase()=="textarea"){var ta=_47;ta.value=Utils.trimLineBreaks(ta.value);ta.value=Utils.trim(ta.value);if(ta.value.length<1){var _48=Utils.getName(ta);var msg=["Required field: ",_48.substring(0,1).toUpperCase(),_48.substring(1)].join("");if(Utils.isNode(_44)){_44.innerHTML=msg;}else{alert(msg);}
return false;}}else{if(_47.nodeName.toLowerCase()=="select"){var sel=_47;if(sel.value.length<1){var _48=Utils.getName(sel);var msg=["Required field: ",_48.substring(0,1).toUpperCase(),_48.substring(1)].join("");if(Utils.isNode(_44)){_44.innerHTML=msg;}else{alert(msg);}
return false;}}else{if(_47.type.toLowerCase()=="password"){var _4c=_47;var _4d=_4c.value.length;var _4e=Utils.trim(_4c.value).length;if(_4d==0){var _48=Utils.getName(_4c);var msg=["Required field: ",_48.substring(0,1).toUpperCase(),_48.substring(1)].join("");if(Utils.isNode(_44)){_44.innerHTML=msg;}else{alert(msg);}
_4c.focus();_4c.select();return false;}
if(_4d!=_4e){var msg="Your password must not contain any whitespace.";if(Utils.isNode(_44)){_44.innerHTML=msg;}else{alert(msg);}
_4c.focus();_4c.select();return false;}}}}}}
return true;},validateFormResolveName:function(_4f,_50){for(var i=0;i<_4f.elements.length;i++){var _52=_4f.elements[i];if("true"!=_52.getAttribute("required")){continue;}
if(_52.type.toLowerCase()=="text"){_52.value=Utils.trim(_52.value);if(_52.value.length<1){var msg=["Required field: ",Utils.getParentName(_52)].join("");if(Utils.isNode(_50)){_50.innerHTML=msg;}else{alert(msg);}
_52.focus();return false;}}else{if(_52.type.toLowerCase()=="textarea"){var ta=_52;ta.value=Utils.trimLineBreaks(ta.value);ta.value=Utils.trim(ta.value);if(ta.value.length<1){var msg=["Required field: ",Utils.getParentName(ta)].join("");if(Utils.isNode(_50)){_50.innerHTML=msg;}else{alert(msg);}
return false;}}else{if(_52.nodeName.toLowerCase()=="select"){var sel=_52;if(sel.value.length<1){var msg=["Required field: ",Utils.getParentName(sel)].join("");if(Utils.isNode(_50)){_50.innerHTML=msg;}else{alert(msg);}
return false;}}else{if(_52.type.toLowerCase()=="password"){var _56=_52;var _57=_56.value.length;var _58=Utils.trim(_56.value).length;if(_57==0){var msg=["Required field: ",Utils.getParentName(_56)].join("");if(Utils.isNode(_50)){_50.innerHTML=msg;}else{alert(msg);}
_56.focus();_56.select();return false;}
if(_57!=_58){var msg="Your password must not contain any whitespace.";if(Utils.isNode(_50)){_50.innerHTML=msg;}else{alert(msg);}
_56.focus();_56.select();return false;}}}}}}
return true;}};var History={handlers:new Array(),currentToken:window.location.hash,loopKey:null,back:function(){if(window.history.length){window.history.back();}},newItem:function(_59){if(_59!=History.currentToken){window.location.hash=_59;}},onHistoryChanged:function(_5a){var h=History.handlers;for(var i in h){h[i](_5a);}},getToken:function(){return History.currentToken;},addHandler:function(_5d){var idx=History.handlers.indexOf(_5d);if(idx==-1){History.handlers.push(_5d);}},loop:function(){var _5f=window.location.hash.substring(1);if(_5f!=History.currentToken){History.currentToken=_5f;History.onHistoryChanged(_5f);}},stop:function(){if(History.loopKey){window.clearInterval(History.loopKey);History.loopKey=null;}},isStarted:function(){return History.loopKey!=null;},start:function(){if(!History.loopKey){History.loopKey=window.setInterval(History.loop,250);}}};if(!Array.prototype.indexOf){Array.prototype.indexOf=function(elt){var len=this.length;var _62=Number(arguments[1])||0;_62=(_62<0)?Math.ceil(_62):Math.floor(_62);if(_62<0){_62+=len;}
for(;_62<len;_62++){if(_62 in this&&this[_62]===elt){return _62;}}
return-1;};}
function JSObject(){var _63=this;this.equals=function(obj){return _63==obj;};function construct(){}
construct();}
function Indexed(){var _65=this;this.__extends=JSObject;this.__extends();var _66=-1;this.setIndex=function(_67){_66=_67;};this.getIndex=function(){return _66;};function construct(){}
construct();}
function AbstractCollection(){var _68=this;this.__extends=JSObject;this.__extends();this.isEmpty=function(){};this.clear=function(){};this.size=function(){};this.get=function(obj){};this.remove=function(obj){};function construct(){}
construct();}
function ArrayList(){var _6b=this;this.__extends=AbstractCollection;this.__extends();var _6c=new Array();this.add=function(obj){if(obj){var idx=_6c.length;_6c.push(obj);_6b._a_onAdd(obj,idx,idx+1);}};this.remove=function(_6f){if(Utils.isNumber(_6f)){return _6f<_6c.length?_6c.splice(_6f,1)[0]:null;}else{if(_6f&&_6f.equals){for(var i in _6c){if(_6c[i].equals(_6f)){var _71=_6c.splice(i,1)[0];_6b._a_onRemove(_71,i,_6c.length);return _71;}}}}
return null;};this.get=function(_72){return _72<_6c.length?_6c[_72]:null;};this.indexOf=function(obj){if(obj){for(var i in _6c){if(_6c[i].equals(obj)){return i;}}}
return-1;};this.contains=function(obj){return _6b.indexOf(obj)!=-1;};this.size=function(){return _6c.length;};this.clear=function(){_6c.splice(0,_6c.length);};this.isEmpty=function(){return _6c.length==0;};this.__wrappedGet=function(){return _6c;};this._a_onAdd=function(obj,_77,_78){};this._a_onRemove=function(obj,_7a,_7b){};function construct(){}
construct();}
function IndexedList(_7c){var _7d=this;this.__extends=ArrayList;this.__extends();var _7e=Utils.isBoolean(_7c)?_7c:true;var _7f=this.add;this.add=function(obj){if(obj){if(!obj.setIndex){obj.setIndex=function(idx){obj.__index=idx;};obj.getIndex=function(){return obj.__index;};}
_7f(obj);}};this._a_onAdd=function(obj,_83,_84){obj.setIndex(_83);};function reflectRemoval(_85,_86){var _87=_7d.__wrappedGet();for(var i=_85;i<_86;i++){_87[i].setIndex(i);}}
this._a_onRemove=function(obj,_8a,_8b){if(_7e){reflectRemoval(_8a,_8b);}};function construct(){}
construct();}
function HashMap(){var _8c=this;this.__extends=AbstractCollection;this.__extends();var _8d={};var _8e=0;this.put=function(key,_90){if(key&&_90){_8d[key]=_90;_8c._a_onPut(key,_90,++_8e);}};this.get=function(key){return key?_8d[key]:null;};this.remove=function(key){if(key){var _93=_8d[key];_8d[key]=null;_8c._a_onRemove(key,_93,--_8e);return _93;}
return null;};this.size=function(){return _8e;};this.clear=function(){_8d={};_8e=0;};this.isEmpty=function(){return _8e==0;};this.__wrappedGet=function(){return _8d;};this._a_onPut=function(key,_95,_96){};this._a_onRemove=function(key,_98,_99){};function construct(){}
construct();}
function IndexedMap(_9a){var _9b=this;this.__extends=HashMap;this.__extends();var _9c=Utils.isBoolean(_9a)?_9a:true;var _9d=this.put;this.put=function(key,_9f){if(_9f){if(!_9f.setIndex){_9f.setIndex=function(idx){_9f.__index=idx;};_9f.getIndex=function(){return _9f.__index;};}
_9d(key,_9f);}};this._a_onPut=function(key,_a2,_a3){_a2.setIndex(_a3-1);};function reflectRemoval(_a4,_a5){var map=_9b.__wrappedGet();var _a7=_a4.getIndex();for(var i in map){var v=map[i];if(v&&v.getIndex()>_a7){v.setIndex(v.getIndex()-1);}}}
this._a_onRemove=function(key,_ab,_ac){if(_9c){reflectRemoval(_ab,_ac);}};function construct(){}
construct();}
function PooledRequest(pl){var _ae=this;this.__extends=JSObject;this.__extends();var _af=pl;var _b0=Utils.newXHR();var _b1=null;this.handle=function(_b2){var _b3=_b1;_b1=null;_af.push(_ae);_b3(_b2);};this.eval=function(_b4){_ae.handle(window.eval(["(",_b4,")"].join("")));};function handleDefault(){if(_b0.readyState==4){if(_b0.status==200){_ae.eval(_b0.responseText);}}}
this.sendCachable=function(url,_b6,_b7,_b8){_b1=_b7;_b0.open(_b8,url,true);_b0.onreadystatechange=handleDefault;_b0.send(_b6);};this.send=function(url,_ba,_bb,_bc){_b1=_bb;_b0.open(_bc,url,true);_b0.onreadystatechange=handleDefault;_b0.setRequestHeader("Content-Type","application/x-www-form-urlencoded");_b0.setRequestHeader("Content-Length",_ba.length);_b0.send(_ba);};this.doGet=function(url,_be,_bf){_ae.sendCachable(url,_be,_bf,"GET");};this.doDelete=function(url,_c1,_c2){_ae.sendCachable(url,_c1,_c2,"DELETE");};this.doPost=function(url,_c4,_c5){_ae.send(url,_c4,_c5,"POST");};this.doPut=function(url,_c7,_c8){_ae.send(url,_c7,_c8,"PUT");};this.getRequest=function(){return _b0;};function construct(){}
construct();}
function RequestPool(_c9){var _ca=this;this.__extends=JSObject;this.__extends();var _cb=new Array();this.push=function(req){_cb.push(req);};this.addNew=function(){_cb.push(new PooledRequest(_ca));};this.send=function(url,_ce,_cf){_cb.shift().send(url,_ce,_cf,"POST");};this.doPut=function(url,_d1,_d2){_cb.shift().doPut(url,_d1,_d2);};this.doPost=function(url,_d4,_d5){_cb.shift().doPost(url,_d4,_d5);};this.doGet=function(url,_d7,_d8){_cb.shift().doGet(url,_d7,_d8);};this.doDelete=function(url,_da,_db){_cb.shift().doDelete(url,_da,_db);};function construct(_dc){var len=_dc?_dc:4;for(var i=0;i<len;i++){_cb.push(new PooledRequest(_ca));}}
construct(_c9);}
function IFrameRequest(){var _df=this;this.__extends=JSObject;this.__extends();var _e0=null;function scheduleRemove(){_e0.removeChild(_e0.firstChild);}
function cleanIFrameDiv(e,_e2){var _e3=null;if(e.currentTarget){_e3=e.currentTarget.contentDocument.body.firstChild.innerHTML;}else{if(e.srcElement){_e3=e.srcElement.contentWindow.document.body.firstChild.innerHTML;}}
if(_e2){_e2(window.eval(["(",_e3,")"].join("")));}}
this.send=function(url,_e5,_e6){var _e7=url.indexOf("?")==-1?"?":"&";var ifr=document.createElement("iframe");Utils.addHandlerToEvent(function(e){cleanIFrameDiv(e,_e6);},ifr,"onload");Utils.applyStyle(ifr,"display:none");ifr.src=[url,_e7,_e5].join("");_e0.appendChild(ifr);};function construct(){_e0=document.createElement("div");Utils.applyStyle(_e0,"display:none");document.body.appendChild(_e0);}
construct();}
function ScriptRequest(){var _ea=this;this.__extends=JSObject;this.__extends();var _eb=null;var _ec=["scr",Utils._script_counter++].join("");var _ed=new Array();this.handle=function(_ee){var _ef=_ed.shift();if(_ef){_ef(_ee);}};this.send=function(url,_f1,_f2){var _f3=url.indexOf("?")==-1?["?callback=",_ec,".handle&"].join(""):["&callback=",_ec,".handle&"].join("");var scr=document.createElement("script");Utils.applyStyle(scr,"display:none");_ed.push(_f2);scr.src=[url,_f3,_f1].join("");_eb.appendChild(scr);};function construct(){window[_ec]=_ea;_eb=document.createElement("div");Utils.applyStyle(_eb,"display:none");document.body.appendChild(_eb);}
construct();}
function CometdClient(u,obj,_f7){var _f8=this;this.__extends=JSObject;this.__extends();var _f9=u.length-1==u.lastIndexOf("/")?u.substring(0,u.length-1):u;var _fa=obj;var _fb=null;var _fc={};var _fd=false;var _fe=false;var _ff=null;var _id=null;function handle(msgs){if(msgs){if(_fe){_fb.send(_f9,"action=reconnect",handle);}else{_fd=false;}
if(Utils.isArray(msgs)){for(var i in msgs){var m=msgs[i];var cb=_fc[m.channel];if(cb){if(_fa&&Utils.isString(cb)){_fa[cb](m);}else{cb(m);}}}}}}
function onConnect(c){_id=c.id;for(var i in c.channels){_fc[c.channels[i]]="tmp";}
_fd=true;if(Utils.isString(_ff)){_fa[_ff]();}else{if(_ff){_ff();}}
_fb.send(_f9,"action=reconnect",handle);}
this.isConnected=function(){return _fd;};this.getId=function(){return _id;};this.start=function(_107){if(!_fd){_ff=_107;_fb.send(_f9,"action=connect",onConnect);}
_fe=true;};this.stop=function(_108){if(_fd){_fd=false;_fb.send(_f9,"action=disconnect",_108?_108:function(){});}
_fe=false;};this.publish=function(_109,data){if(_fd){if(_109.lastIndexOf("/")==_109.length-1){_109=_109.substring(0,_109.length-1);}
var ch=_fc[_109];if(ch){_fb.send(_f9+_109+"?action=publish",data,handle);}}};this.subscribe=function(_10c,_10d){if(_fd){if(_10c.lastIndexOf("/")==_10c.length-1){_10c=_10c.substring(0,_10c.length-1);}
var old=_fc[_10c];_fc[_10c]=_10d;if(!old){_fb.send(_f9+_10c,"action=subscribe",handle);}}};this.unsubscribe=function(_10f){if(_fd){if(_10f.lastIndexOf("/")==_10f.length-1){_10f=_10f.substring(0,_10f.length-1);}
var ch=_fc[_10f];if(ch){chanels[_10f]=null;_fb.send(_f9+_10f,"action=unsubscribe",handle);}}};function construct(u,obj,type){if(type){if(type=="iframe"){_fb=new IFrameRequest();}else{if(type=="script"){_fb=new ScriptRequest();}else{if(type=="xhr"){_fb=new RequestPool(5);}}}}
if(!_fb){_fb=new RequestPool(5);}}
construct(u,obj,_f7);}
var DragUtil={getInitialLeft:function(el){if(el.style.left){return parseInt(el.style.left);}
var left=Utils.getCssStyle(el,"left");var idx=left.indexOf("px");return idx==-1?0:parseInt(left.substring(0,idx));},getInitialTop:function(el){if(el.style.top){return parseInt(el.style.top);}
var top=Utils.getCssStyle(el,"top");var idx=top.indexOf("px");return idx==-1?0:parseInt(top.substring(0,idx));},_draggables:new HashMap(),_dropabbles:new HashMap(),addDrag:function(el,drag){DragUtil._draggables.put(el,drag);},addDragDrop:function(el,_11d){DragUtil._droppables.put(el,_11d);},_front:null,bringToFront:function(_11e){if(Utils.isNode(_11e)){_11e=_11e.__drag;}
if(_11e&&_11e.bringToFront){if(DragUtil._front){DragUtil._front.bringToBack();}
DragUtil._front=_11e;_11e.bringToFront();}}};function Draggable(el,_120){var _121=this;this.__extends=JSObject;this.__extends();var _el=null;var _123=0;var _124=0;var _125=null;var _126=null;var _127=null;var _128=null;this.getElement=function(){return _el;};this.bringToFront=function(){_el.style.zIndex=10000;};this.bringToBack=function(){_el.style.zIndex=_125;};this.reset=function(){if(_128){if(_127!="absolute"&&_127!="fixed"){_el.style.left=[_128.relX,"px"].join("");_el.style.top=[_128.relY,"px"].join("");}else{_el.style.left=[_128.initX,"px"].join("");_el.style.top=[_128.initY,"px"].join("");}}};function mouseMove(e){if(!e){e=window.event;}
_el.style.left=[_123+e.clientX,"px"].join("");_el.style.top=[_124+e.clientY,"px"].join("");}
function mouseUp(e){document.onmousemove=null;document.onselectstart=null;document.onmouseup=null;}
function mouseDown(e){if(!e){e=window.event;}
var el=e.target?e.target:e.srcElement;if(el!=_126){if(el==_el){DragUtil.bringToFront(_121);}
return;}
if(_127!="absolute"&&_127!="fixed"){if(!_128){_128=Utils.getCoords(_el);_128.relX=DragUtil.getInitialLeft(_el);_128.relY=DragUtil.getInitialTop(_el);_123=_128.relX-e.clientX;_124=_128.relY-e.clientY;}else{var _12d=_el.style.left?parseInt(_el.style.left):0;var _12e=_el.style.top?parseInt(_el.style.top):0;_123=_12d-e.clientX;_124=_12e-e.clientY;}}else{if(!_128){_128=Utils.getCoords(_el);_128.initX=DragUtil.getInitialLeft(_el);_128.initY=DragUtil.getInitialTop(_el);}
_123=_el.offsetLeft-e.clientX;_124=_el.offsetTop-e.clientY;}
DragUtil.bringToFront(_121);document.onmouseup=mouseUp;document.onmousemove=mouseMove;document.body.focus();document.onselectstart=function(){return false;};return false;}
function construct(el,_130){_el=el;_el.onmousedown=mouseDown;_el.style.cursor="default";_125=Utils.getZIndex(_el);_126=_130;if(_126){_126.style.cursor="default";}else{_126=_el;}
_127=_el.style.position?_el.style.position:Utils.getCssStyle(_el,"position");if(_127!="absolute"&&_127!="fixed"){_el.style.position="relative";}
_el.__drag=_121;DragUtil.addDrag(_el,_121);}
construct(el,_120);}
function DraggableBounded(el,_132,_133){var _134=this;this.__extends=JSObject;this.__extends();var _el=null;var _136=0;var _137=0;var _138=null;var _139=null;var _13a=null;var _13b=null;var _13c=null;var _13d=null;var _13e=null;this.getElement=function(){return _el;};this.bringToFront=function(){_el.style.zIndex=10000;};this.bringToBack=function(){_el.style.zIndex=_138;};this.reset=function(){if(_13b){if(_13a!="absolute"&&_13a!="fixed"){_el.style.left=[_13b.relX,"px"].join("");_el.style.top=[_13b.relY,"px"].join("");}else{_el.style.left=[_13b.initX,"px"].join("");_el.style.top=[_13b.initY,"px"].join("");}}};function mouseMove(e){if(!e){e=window.event;}
var x=_136+e.clientX+_13b.x-_13b.relX+_13e.x;var y=_137+e.clientY+_13b.y-_13b.relY+_13e.y;if(_13d.xa<x+1&&_13d.ya<y+1&&_13d.xb>x-1+_el.offsetWidth&&_13d.yb>y-1+_el.offsetHeight){_el.style.left=[_136+e.clientX,"px"].join("");_el.style.top=[_137+e.clientY,"px"].join("");}}
function mouseUp(e){document.onmousemove=null;document.onselectstart=null;document.onmouseup=null;}
function mouseDown(e){if(!e){e=window.event;}
var el=e.target?e.target:e.srcElement;if(el!=_139){if(el==_el){DragUtil.bringToFront(_134);}
return;}
if(_13a!="absolute"&&_13a!="fixed"){if(!_13b){_13e={x:0,y:0};_13b=Utils.getCoords(_el);_13b.relX=DragUtil.getInitialLeft(_el);_13b.relY=DragUtil.getInitialTop(_el);if(_13c==document.body){_parentCoords={x:0,y:0,relX:0,relY:0};_13d={xa:_parentCoords.x,xb:_parentCoords.x+document.body.clientWidth,ya:_parentCoords.y,yb:document.body.clientHeight};}else{_parentCoords=Utils.getCoords(_13c);_parentCoords.relX=0;_parentCoords.relY=0;_13d={xa:_parentCoords.x,xb:_parentCoords.x+_13c.offsetWidth,ya:_parentCoords.y,yb:_parentCoords.y+_13c.offsetHeight};}
_136=_13b.relX-e.clientX;_137=_13b.relY-e.clientY;}else{var _145=_el.style.left?parseInt(_el.style.left):0;var _146=_el.style.top?parseInt(_el.style.top):0;_136=_145-e.clientX;_137=_146-e.clientY;}}else{if(!_13b){_13b=Utils.getCoords(_el);_13b.initX=DragUtil.getInitialLeft(_el);_13b.initY=DragUtil.getInitialTop(_el);if(_13c==document.body){_parentCoords={x:0,y:0,relX:0,relY:0};_13e={x:0,y:0};_13d={xa:_parentCoords.x,xb:_parentCoords.x+document.body.clientWidth,ya:_parentCoords.y,yb:document.body.clientHeight};}else{_parentCoords=Utils.getCoords(_13c);_parentCoords.relX=DragUtil.getInitialLeft(_13c);_parentCoords.relY=DragUtil.getInitialTop(_13c);var pos=_13c.style.position?_13c.style.position:Utils.getCssStyle(_13c,"position");if(pos=="static"){_13e={x:0,y:0};}else{_13e=_parentCoords;}
_13d={xa:_parentCoords.x,xb:_parentCoords.x+_13c.offsetWidth,ya:_parentCoords.y,yb:_parentCoords.y+_13c.offsetHeight};}}
_136=_el.offsetLeft-e.clientX;_137=_el.offsetTop-e.clientY;}
DragUtil.bringToFront(_134);document.onmouseup=mouseUp;document.onmousemove=mouseMove;document.body.focus();document.onselectstart=function(){return false;};return false;}
function construct(el,_149,_14a){_el=el;_el.onmousedown=mouseDown;_el.style.cursor="default";_138=Utils.getZIndex(_el);_139=_149;if(_139){_139.style.cursor="default";}else{_139=_el;}
_13a=_el.style.position?_el.style.position:Utils.getCssStyle(_el,"position");if(_13a!="absolute"&&_13a!="fixed"){_el.style.position="relative";}
_13c=Utils.isNode(_14a)?_14a:_el.parentNode;_el.__drag=_134;DragUtil.addDrag(_el,_134);}
construct(el,_132,_133);}
function DraggableProxy(el,_14c,_14d,_14e,_14f){var _150=this;this.__extends=JSObject;this.__extends();var _el=null;var _152=0;var _153=0;var _154=null;var _155=null;var _156=null;var _157=null;var _158=null;var _159=true;var _15a=true;this.getElement=function(){return _el;};this.bringToFront=function(){_el.style.zIndex=10000;};this.bringToBack=function(){_el.style.zIndex=_154;};this.setResizeProxy=function(_15b){_159=_15b;};this.isResizeProxy=function(){return _159;};this.setMoveOriginal=function(_15c){_15a=_15c;};this.isMoveOriginal=function(){return _15a;};this.reset=function(){if(_157){if(_156!="absolute"&&_156!="fixed"){_el.style.left=[_157.relX,"px"].join("");_el.style.top=[_157.relY,"px"].join("");}else{_el.style.left=[_157.initX,"px"].join("");_el.style.top=[_157.initY,"px"].join("");}}};function mouseMove(e){if(!e){e=window.event;}
_158.style.display="";_158.style.left=[_152+e.clientX+_157.x-_157.relX,"px"].join("");_158.style.top=[_153+e.clientY+_157.y-_157.relY,"px"].join("");}
function mouseUp(e){document.onmousemove=null;document.onselectstart=null;document.onmouseup=null;if(_15a){var x=parseInt(_158.style.left);var y=parseInt(_158.style.top);_el.style.left=[x-_157.x+_157.relX,"px"].join("");_el.style.top=[y-_157.y+_157.relY,"px"].join("");}
_158.style.zIndex=null;_158.style.display="none";}
function mouseDown(e){if(!e){e=window.event;}
var el=e.target?e.target:e.srcElement;if(el!=_155){if(el==_el){DragUtil.bringToFront(_150);}
return;}
if(_156!="absolute"&&_156!="fixed"){if(!_157){_157=Utils.getCoords(_el);_157.relX=DragUtil.getInitialLeft(_el);_157.relY=DragUtil.getInitialTop(_el);_152=_157.relX-e.clientX;_153=_157.relY-e.clientY;}else{var _163=_el.style.left?parseInt(_el.style.left):0;var _164=_el.style.top?parseInt(_el.style.top):0;_152=_163-e.clientX;_153=_164-e.clientY;}}else{if(!_157){_157={x:0,y:0,relX:0,relY:0};_157.initX=DragUtil.getInitialLeft(_el);_157.initY=DragUtil.getInitialTop(_el);}
_152=_el.offsetLeft-e.clientX;_153=_el.offsetTop-e.clientY;}
_154=_el.style.zIndex;if(_159){_158.style.width=[_el.offsetWidth,"px"].join("");_158.style.height=[_el.offsetHeight,"px"].join("");}
DragUtil.bringToFront(_150);_158.style.zIndex=10000;document.onmouseup=mouseUp;document.onmousemove=mouseMove;document.body.focus();document.onselectstart=function(){return false;};return false;}
function construct(el,_166,_167,_168,_169){_el=el;_el.onmousedown=mouseDown;_el.style.cursor="default";_154=Utils.getZIndex(_el);_155=_166;if(_155){_155.style.cursor="default";}else{_155=_el;}
_156=_el.style.position?_el.style.position:Utils.getCssStyle(_el,"position");if(_156!="absolute"&&_156!="fixed"){_el.style.position="relative";}
_158=document.createElement("div");if(_167){_158.className=_167;}
_158.style.position="absolute";_158.style.display="none";document.body.appendChild(_158);if(Utils.isBoolean(_169)){_159=_169;}
if(Utils.isBoolean(_168)){_15a=_168;}
_el.__drag=_150;DragUtil.addDrag(_el,_150);}
construct(el,_14c,_14d,_14e,_14f);}
function DraggableProxyBounded(el,_16b,_16c,_16d,_16e,_16f){var _170=this;this.__extends=JSObject;this.__extends();var _el=null;var _172=0;var _173=0;var _174=null;var _175=null;var _176=null;var _177=null;var _178=null;var _179=null;var _17a=null;var _17b=null;var _17c=true;var _17d=true;var _17e=null;this.getElement=function(){return _el;};this.bringToFront=function(){_el.style.zIndex=10000;};this.bringToBack=function(){_el.style.zIndex=_174;};this.setResizeProxy=function(_17f){_17c=_17f;};this.isResizeProxy=function(){return _17c;};this.setMoveOriginal=function(_180){_17d=_180;};this.isMoveOriginal=function(){return _17d;};this.setContainer=function(_181){if(Utils.isNode(_181)){_17e=_181;}};this.getContainer=function(){return _17e;};this.reset=function(){if(_177){if(_176!="absolute"&&_176!="fixed"){_el.style.left=[_177.relX,"px"].join("");_el.style.top=[_177.relY,"px"].join("");}else{_el.style.left=[_177.initX,"px"].join("");_el.style.top=[_177.initY,"px"].join("");}}};function mouseMove(e){if(!e){e=window.event;}
_178.style.display="";var x=_172+e.clientX+_177.x-_177.relX+_17b.x;var y=_173+e.clientY+_177.y-_177.relY+_17b.y;if(_17a.xa<x+1&&_17a.ya<y+1&&_17a.xb>x-1+_el.offsetWidth&&_17a.yb>y-1+_el.offsetHeight){_178.style.left=[x,"px"].join("");_178.style.top=[y,"px"].join("");}}
function mouseUp(e){document.onmousemove=null;document.onselectstart=null;document.onmouseup=null;if(_17d){var x=parseInt(_178.style.left);var y=parseInt(_178.style.top);_el.style.left=[x-_177.x+_177.relX-_17b.x,"px"].join("");_el.style.top=[y-_177.y+_177.relY-_17b.y,"px"].join("");}
_178.style.zIndex=null;_178.style.display="none";}
function mouseDown(e){if(!e){e=window.event;}
var el=e.target?e.target:e.srcElement;if(el!=_175){if(el==_el){DragUtil.bringToFront(_170);}
return;}
if(_176!="absolute"&&_176!="fixed"){if(!_177){_17b={x:0,y:0};_177=Utils.getCoords(_el);_177.relX=DragUtil.getInitialLeft(_el);_177.relY=DragUtil.getInitialTop(_el);if(_17e==document.body){_179={x:0,y:0,relX:0,relY:0};_17a={xa:_179.x,xb:_179.x+document.body.clientWidth,ya:_179.y,yb:document.body.clientHeight};}else{_179=Utils.getCoords(_17e);_179.relX=0;_179.relY=0;_17a={xa:_179.x,xb:_179.x+_17e.offsetWidth,ya:_179.y,yb:_179.y+_17e.offsetHeight};}
_172=_177.relX-e.clientX;_173=_177.relY-e.clientY;}else{var _18a=_el.style.left?parseInt(_el.style.left):0;var _18b=_el.style.top?parseInt(_el.style.top):0;_172=_18a-e.clientX;_173=_18b-e.clientY;}}else{if(!_177){_177={x:0,y:0,relX:0,relY:0};_177.initX=DragUtil.getInitialLeft(_el);_177.initY=DragUtil.getInitialTop(_el);if(_17e==document.body){_179={x:0,y:0,relX:0,relY:0};_17b={x:0,y:0};_17a={xa:_179.x,xb:_179.x+document.body.clientWidth,ya:_179.y,yb:document.body.clientHeight};}else{_179=Utils.getCoords(_17e);_179.relX=DragUtil.getInitialLeft(_17e);_179.relY=DragUtil.getInitialTop(_17e);var pos=_17e.style.position?_17e.style.position:Utils.getCssStyle(_17e,"position");if(pos=="static"){_17b={x:0,y:0};}else{_17b=_179;}
_17a={xa:_179.x,xb:_179.x+_17e.offsetWidth,ya:_179.y,yb:_179.y+_17e.offsetHeight};}}
_172=_el.offsetLeft-e.clientX;_173=_el.offsetTop-e.clientY;}
if(_17c){_178.style.width=[_el.offsetWidth,"px"].join("");_178.style.height=[_el.offsetHeight,"px"].join("");}
DragUtil.bringToFront(_170);_178.style.zIndex=10000;document.onmouseup=mouseUp;document.onmousemove=mouseMove;document.body.focus();document.onselectstart=function(){return false;};return false;}
function construct(el,_18e,_18f,_190,_191,_192){_el=el;_el.onmousedown=mouseDown;_el.style.cursor="default";_174=Utils.getZIndex(_el);_175=_18e;if(_175){_175.style.cursor="default";}else{_175=_el;}
_176=_el.style.position?_el.style.position:Utils.getCssStyle(_el,"position");if(_176!="absolute"&&_176!="fixed"){_el.style.position="relative";}
_178=document.createElement("div");if(_190){_178.className=_190;}
_178.style.position="absolute";_178.style.display="none";document.body.appendChild(_178);if(Utils.isBoolean(_192)){_17c=_192;}
if(Utils.isBoolean(_191)){_17d=_191;}
_17e=Utils.isNode(_18f)?_18f:_el.parentNode;_el.__drag=_170;DragUtil.addDrag(_el,_170);}
construct(el,_16b,_16c,_16d,_16e,_16f);}
var WidgetFactory={create:function(_193,_194,_195){if(Utils.isString(_193)){_193=document.createElement(_193);}
if(Utils.isNode(_193)){if(_194){_193.innerHTML=_194;}
return new SimpleWidget(_193,_195);}
return null;},createInput:function(type,_197){var _198=document.createElement("input");_198.setAttribute("type",type);return WidgetFactory.create(_198,null,_197);},createById:function(id){var node=document.getElementById(id);return Utils.isNode(node)?(Utils.isWidget(node.__wrapper)?node.__wrapper:new SimpleWidget(node)):null;}};function SimpleWidget(el,_19c){var _19d=this;this.__extends=Indexed;this.__extends();var _19e=null;var _19f=null;var _1a0=new Array();var _1a1=null;this.setAttribute=function(name,_1a3){if(!_1a1){_1a1=new HashMap();}
_1a1.put(name,_1a3);};this.getAttribute=function(name){if(!_1a1){_1a1=new HashMap();}
return _1a1.get(name);};this.removeAttribute=function(name){if(!_1a1){_1a1=new HashMap();}
return _1a1.remove(name);};this.getAttributeMap=function(){return _1a1;};this.isSimple=function(){return true;};this.props={};this.setElement=function(el){if(!_19e&&Utils.isNode(el)){_19e=el;if(_19e.__wrapper){_1a0=_19e.__wrapper.getStyles();_1a1=_19e.__wrapper.getAttributeMap();}
_19e.__wrapper=_19d;}};this.getElement=function(){return _19e;};this.setParent=function(p){if(_19f){_19f._a_removeChildElement(_19e);_19d._a_onDetach();}
if(Utils.isString(p)){p=document.getElementById(p);}
if(Utils.isNode(p)){_19f=Utils.isWidget(p.__wrapper)?p.__wrapper:new SimpleWidget(p);_19f._a_appendChildElement(_19e);_19d._a_onAttach();}else{if(Utils.isWidget(p)){_19f=p;_19f._a_appendChildElement(_19e);this._a_onAttach();}else{_19f=null;}}};this.getParent=function(){return _19f;};this.setId=function(id){_19e.id=id;};this.getId=function(){return _19e.id;};this.setName=function(name){_19e.name=name;};this.getName=function(){return _19e.name;};this.setTitle=function(_1aa){_19e.title=_1aa;};this.getTitle=function(){return _19e.title;};this.setStyle=function(_1ab){if(_1ab){if(_1a0.length>0){_1a0.splice(0,_1a0.length);}
_1a0.push(_1ab);_19e.className=_1ab;}};this.addStyle=function(_1ac){if(_1ac&&_1a0.indexOf(_1ac)==-1){_1a0.push(_1ac);_19e.className=_1a0.length>1?_1a0.join(" "):_1a0[0];}};this.removeStyle=function(_1ad){var idx=_1ad?_1a0.indexOf(_1ad):-1;if(idx!=-1){_1a0.splice(idx,1);_19e.className=_1a0.length>1?_1a0.join(" "):_1a0[0];return true;}
return false;};this.getStyle=function(){return _19e.className;};this.getStyles=function(){return _1a0;};this.setStyleProperty=function(name,_1b0){_19e.style[name]=_1b0;};this.getStyleProperty=function(name){return _19e.style[name];};this.setElementProperty=function(name,_1b3){_19e[name]=_1b3;};this.getElementProperty=function(name){return _19e[name];};this.isAttached=function(){return _19f!=null;};this.addEventHandler=function(_1b5,_1b6){Utils.addHandlerToEvent(_1b6,_19e,_1b5);};this._a_appendChildElement=function(_1b7){_19e.appendChild(_1b7);};this._a_removeChildElement=function(_1b8){_19e.removeChild(_1b8);};this.setVisible=function(_1b9){_19e.style.display=_1b9?"":"none";};this.isVisible=function(){return _19e.style.display!="none";};this.toggle=function(){_19e.style.display=_19e.style.display=="none"?"":"none";};this._a_onAttach=function(){};this._a_onDetach=function(){};function construct(el,_1bb){if(Utils.isNode(el)){_19d.setElement(el);_19d.setStyle(_1bb);}}
construct(el,_19c);}
function AbstractWrapperWidget(){var _1bc=this;this.__extends=SimpleWidget;this.__extends();var _1bd=null;this.setChild=function(_1be){if(Utils.isWidget(_1be)&&!_1bc.equals(_1be.getParent())){_1bd=_1be;_1bd.setParent(_1bc);}};this.getChild=function(){return _1bd;};this.onlyChild=function(){return _1bd;};this.addChild=function(_1bf){_1bc.setChild(_1bf);};function construct(){}
construct();}
function AbstractContainerWidget(){var _1c0=this;this.__extends=SimpleWidget;this.__extends();var _1c1=new ArrayList();this.getChildren=function(){return _1c1;};this.size=function(){return _1c1.size();};this.getChild=function(_1c2){return _1c1.get(_1c2);};this.addChild=function(_1c3){if(Utils.isWidget(_1c3)&&!_1c0.equals(_1c3.getParent())){var _1c4=_1c1.size();_1c3=_1c0._a_filterAddCandidate(_1c3);if(_1c3){_1c1.add(_1c3);_1c3.setParent(_1c0);_1c0._a_onChildAdded(_1c3,_1c4);}}};this.removeChild=function(_1c5){var _1c6=_1c1.remove(_1c5);if(_1c6){_1c6.setParent(null);_1c0._a_onChildRemoved(_1c6,_1c5);}
return _1c6;};this.removeChildren=function(_1c7,_1c8){var size=_1c1.size();var end=_1c8?(_1c8>size?size:_1c8):size;var _1cb=_1c7?(_1c7<end?_1c7:end):0;for(var i=0,len=end-_1cb;i<len;i++){_1c0.removeChild(_1cb);}};this._a_filterAddCandidate=function(_1ce){return _1ce;};this._a_onChildAdded=function(_1cf,_1d0){};this._a_onChildRemoved=function(_1d1,_1d2){};function construct(){}
construct();}
function CustomWidget(){var _1d3=this;this.__extends=SimpleWidget;this.__extends();var _1d4=null;this.isSimple=function(){return false;};this.setWidget=function(_1d5){if(!_1d4&&Utils.isWidget(_1d5)){_1d4=_1d5;_1d3.setElement(_1d4.getElement());}};this.getWidget=function(){return _1d4;};this._a_onAttach=function(){_1d4.setParent(_1d3.getParent());};function construct(){}
construct();}
function SimplePanel(_1d6,_1d7){var _1d8=this;this.__extends=AbstractWrapperWidget;this.__extends();function construct(_1d9,_1da){_1d8.setElement(document.createElement("div"));_1d8.setStyle(_1da);_1d8.setChild(_1d9);}
construct(_1d6,_1d7);}
function SimpleCellPanel(_1db){var _1dc=this;this.__extends=AbstractWrapperWidget;this.__extends();var _td=null;this._a_appendChildElement=function(_1de){_td.appendChild(_1de);};this._a_removeChildElement=function(_1df){_td.removeChild(_1df);};this.setBorder=function(_1e0){_1dc.setElementProperty("border",_1e0);};this.setSpacing=function(_1e1){_1dc.setElementProperty("cellSpacing",_1e1);};this.setPadding=function(_1e2){_1dc.setElementProperty("cellPadding",_1e2);};function construct(_1e3){var _1e4=document.createElement("table");var _1e5=document.createElement("tbody");var tr=document.createElement("tr");_td=document.createElement("td");tr.appendChild(_td);_1e5.appendChild(tr);_1e4.appendChild(_1e5);_1dc.setElement(_1e4);_1dc.setElementProperty("cellPadding",0);_1dc.setElementProperty("cellSpacing",0);_1dc.setChild(_1e3);}
construct(_1db);}
function CenterPanel(_1e7,_1e8){var _1e9=this;this.__extends=AbstractWrapperWidget;this.__extends();function construct(_1ea,_1eb){_1e9.setElement(document.createElement("center"));_1e9.setStyle(_1eb);_1e9.setChild(_1ea);}
construct(_1e7,_1e8);}
function FlowPanel(_1ec){var _1ed=this;this.__extends=AbstractContainerWidget;this.__extends();function construct(_1ee){_1ed.setElement(document.createElement("div"));_1ed.setStyle(_1ee);}
construct(_1ec);}
function AbstractCellPanel(){var _1ef=this;this.__extends=AbstractContainerWidget;this.__extends();var _1f0=null;var _1f1={top:"vertical-align: top;",middle:"vertical-align: middle;",bottom:"vertical-align: bottom;"};var _1f2={left:"left",center:"center",right:"right"};this.getTBODY=function(){return _1f0;};this._a_filterAddCandidate=function(_1f3){var _1f4=new SimpleWidget(document.createElement("td"));_1f4.setElementProperty("align",_1f2["left"]);Utils.applyStyle(_1f4.getElement(),_1f1["top"]);_1f3.setParent(_1f4);return _1f4;};this._a_onChildAdded=function(_1f5,_1f6){_1f5.setIndex(_1f6);};this.setVerticalAlign=function(_1f7,_1f8){var al=_1f1[_1f8];if(al&&Utils.isWidget(_1f7)){var td=_1f7.getParent();if(td&&_1ef.equals(td.getParent())){Utils.applyStyle(td.getElement(),al);}}};this.setHorizontalAlign=function(_1fb,_1fc){var al=_1f2[_1fc];if(al&&Utils.isWidget(_1fb)){var td=_1fb.getParent();if(td&&_1ef.equals(td.getParent())){td.setElementProperty("align",al);}}};this.setCellWidth=function(_1ff,_200){if(Utils.isWidget(_1ff)){var td=_1ff.getParent();if(td&&_1ef.equals(td.getParent())){td.setElementProperty("width",_200);}}};this.setCellHeight=function(_202,_203){if(Utils.isWidget(_202)){var td=_202.getParent();if(td&&_1ef.equals(td.getParent())){td.setElementProperty("height",_203);}}};this.setBorder=function(_205){_1ef.setElementProperty("border",_205);};this.setSpacing=function(_206){_1ef.setElementProperty("cellSpacing",_206);};this.setPadding=function(_207){_1ef.setElementProperty("cellPadding",_207);};function construct(){_1f0=document.createElement("tbody");var _208=document.createElement("table");_208.appendChild(_1f0);_1ef.setElement(_208);}
construct();}
function VerticalCellPanel(){var _209=this;this.__extends=AbstractCellPanel;this.__extends();this._a_appendChildElement=function(_20a){var tr=document.createElement("tr");tr.appendChild(_20a);_209.getTBODY().appendChild(tr);};this._a_removeChildElement=function(_20c){var tr=_20c.parentNode;tr.removeChild(_20c);_209.getTBODY().removeChild(tr);};function construct(){_209.setElementProperty("cellSpacing",0);_209.setElementProperty("cellPadding",0);}
construct();}
function HorizontalCellPanel(){var _20e=this;this.__extends=AbstractCellPanel;this.__extends();var _tr=null;this.getTR=function(){return _tr;};this._a_appendChildElement=function(_210){_tr.appendChild(_210);};this._a_removeChildElement=function(_211){_tr.removeChild(_211);};function construct(){_20e.setElementProperty("cellSpacing",0);_20e.setElementProperty("cellPadding",0);_tr=document.createElement("tr");_20e.getTBODY().appendChild(_tr);}
construct();}
function DeckPanel(){var _212=this;this.__extends=AbstractContainerWidget;this.__extends();var _213=null;function styleChild(_214,_215,_216){_214.setStyleProperty("display",_215);}
this._a_onChildAdded=function(_217,_218){styleChild(_217,"none","100%");};this._a_onChildRemoved=function(_219,_21a){styleChild(_219,"","");};this.show=function(_21b){var _21c=_212.getChild(_21b);if(_21c){if(_213){_213.setStyleProperty("display","none");}
_213=_21c;_213.setStyleProperty("display","");}else{if(_213){_213.setStyleProperty("display","none");_213=null;}}};this.getCurrentWidget=function(){return _213;};function construct(){_212.setElement(document.createElement("div"));}
construct();}
function AbstractListPanel(){var _21d=this;this.__extends=AbstractContainerWidget;this.__extends();this._a_filterAddCandidate=function(_21e){var li=new SimpleWidget(document.createElement("li"));_21e.setParent(li);return li;};function construct(){_21d.setElement(document.createElement("ul"));Utils.applyStyle(_21d.getElement(),"margin:0; padding:0; list-style:none;");}
construct();}
function VerticalListPanel(){var _220=this;this.__extends=AbstractListPanel;this.__extends();this._a_onChildAdded=function(_221,_222){_221.setIndex(_222);};function construct(){}
construct();}
function HorizontalListPanel(){var _223=this;this.__extends=AbstractListPanel;this.__extends();this._a_onChildAdded=function(_224,_225){_224.setIndex(_225);_224.setStyleProperty("display","inline");_224.getElement().firstChild.style.display="inline";};this._a_onChildRemoved=function(_226,_227){_226.setStyleProperty("display","");_226.getElement().firstChild.style.display="";};function construct(){}
construct();}
function PopupPanel(_228){var _229=this;this.__extends=AbstractContainerWidget;this.__extends();this.center=function(){Utils.positionCenter(_229.getElement());};this.setPosition=function(left,top){var x=Utils.isNumber(left)?[left,"px"].join(""):left;var y=Utils.isNumber(top)?[top,"px"].join(""):top;_229.setStyleProperty("left",x);_229.setStyleProperty("top",y);};this.show=function(){_229.setVisible(true);};this.isHidden=function(){return!_229.isVisible();};this.hide=function(){_229.setVisible(false);};function construct(_22e){var div=document.createElement("div");_229.setElement(div);_229.setVisible(false);_229.setStyle(_22e);_229.setStyleProperty("position","absolute");}
construct(_228);}
function SimpleTable(rows,cols,_232){var _233=this;this.__extends=SimpleWidget;this.__extends();var _234={top:"vertical-align: top;",middle:"vertical-align: middle;",bottom:"vertical-align: bottom;"};var _235={left:"left",center:"center",right:"right"};var _236=null;var _237=null;this.setWidget=function(row,col,_23a){if(_236>row&&_237>col){var cell=_233.getElement().rows[row].cells[col];Utils.refreshElement(cell);if(Utils.isWidget(_23a)){cell.appendChild(_23a.getElement());}}};this.getWidget=function(row,col){if(_236>row&&_237>col){var _23e=_233.getElement().rows[row].cells[col].firstChild;return _23e&&Utils.isWidget(_23e.__wrapper)?_23e.__wrapper:null;}
return null;};this.setRowStyle=function(row,_240){if(_236>row){_233.getElement().rows[row].className=_240;}};this.setCellStyle=function(row,col,_243){if(_236>row&&_237>col){_233.getElement().rows[row].cells[col].className=_243;}};this.styleOddEvenRows=function(_244,_245,_246,_247){var end=_247?(_247>_236?_236:_247):_236;var _249=_246?(_246<end?_246:end):0;for(var i=0,len=end-_249;i<len;i++,_249++){_233.getElement().rows[_249].className=_249%2==0?_245:_244;}};this.addRow=function(){var tr=_233.getElement().insertRow(_236);for(var j=0;j<_237;j++){tr.insertCell(j);}
return _236++;};this.insertRow=function(row){if(row<_236){var tr=_233.getElement().insertRow(row);for(var j=0;j<_237;j++){tr.insertCell(j);}
return _236++;}
return _236;};this.removeRow=function(row){if(row<_236){_233.getElement().deleteRow(row);_236--;return true;}
return false;};this.removeRows=function(_252,_253){var end=_253?(_253>_236?_236:_253):_236;var _255=_252?(_252<end?_252:end):0;for(var i=0,len=end-_255;i<len;i++,_236--){_233.getElement().deleteRow(_255);}};this.getTD=function(row,col){return _236>row&&_237>col?_233.getElement().rows[row].cells[col]:null;};this.getTR=function(row){return _236>row?_233.getElement().rows[row]:null;};this.getRowCount=function(){return _236;};this.setBorder=function(_25b){_233.setElementProperty("border",_25b);};this.setSpacing=function(_25c){_233.setElementProperty("cellSpacing",_25c);};this.setPadding=function(_25d){_233.setElementProperty("cellPadding",_25d);};this.setVerticalAlign=function(row,col,_260){var al=_234[_260];var td=_233.getTD(row,col);if(al&&td){Utils.applyStyle(td,al);}};this.setHorizontalAlign=function(row,col,_265){var al=_235[_265];var td=_233.getTD(row,col);if(al&&td){td["align"]=al;}};this.setCellWidth=function(row,col,_26a){var td=_233.getTD(row,col);if(td){td["width"]=_26a;}};this.setCellHeight=function(row,col,_26e){var td=_233.getTD(row,col);if(td){td["height"]=_26e;}};function construct(rows,cols,_272){var _273=document.createElement("table");_236=rows||0;_237=cols||0;for(var i=0;i<_236;i++){var tr=_273.insertRow(i);for(var j=0;j<cols;j++){tr.insertCell(j);}}
_233.setElement(_273);_233.setStyle(_272);_233.setElementProperty("cellSpacing",0);_233.setElementProperty("cellPadding",0);}
construct(rows,cols,_232);}
function Hyperlink(_277,_278,_279){var _27a=this;this.__extends=SimpleWidget;this.__extends();function construct(_27b,_27c,_27d){var a=document.createElement("a");if(Utils.isString(_27b)){a.innerHTML=_27b;}else{if(Utils.isNode(_27b)){a.appendChild(_27b);}else{if(Utils.isWidget(_27b)){a.appendChild(_27b.getElement());}}}
a.href=["#",_27c].join("");_27a.setElement(a);_27a.setStyle(_27d);}
construct(_277,_278,_279);}
function SelectBox(_27f){var _280=this;this.__extends=SimpleWidget;this.__extends();var _281="";var _282=new Array();var _283=this.setElementProperty;this.setElementProperty=function(name,_285){if(name!="value"){_283(name,_285);return;}
_280.getElement().selectedIndex=0;};var _286=this.getElementProperty;this.getElementProperty=function(name){return name!="value"?_286(name):_280.getValue();};var _288=this.addEventHandler;this.addEventHandler=function(_289,_28a){if(_289!="onchange"){_288(_289,_28a);return;}
_282.push(_28a);};this.getValue=function(){if(_280.size()>0){var sel=_280.getElement();_281=sel.options[sel.selectedIndex].value;}else{_281="";}
return _281;};this.size=function(){return _280.getElement().options.length;};this.addEntry=function(_28c,_28d){var _28e=document.createElement("option");_28e.value=_28c;_28e.innerHTML=_28d;_280.getElement().appendChild(_28e);};this.removeEntry=function(idx){if(idx<_280.getElement().options.length){_280.getElement().remove(idx);return true;}
return false;};this.removeEntries=function(_290,_291){var size=_280.size();var end=_291?(_291>_rows?size:_291):size;var _294=_290?(_290<end?_290:end):0;for(var i=0,len=end-_294;i<len;i++){_280.getElement().remove(_294);}};function onChange(e){var sel=_280.getElement();_281=sel.options[sel.selectedIndex].value;for(var i in _282){_282[i](e,_281);}}
function construct(_29a){var _29b=document.createElement("select");Utils.addHandlerToEvent(onChange,_29b,"onchange");_280.setElement(_29b);if(_29a){_280.addEntry("","");}}
construct(_27f);}
function AbstractPane(){var _29c=this;this.__extends=FlowPanel;this.__extends();var _29d=null;var _29e=null;var _29f=null;var _2a0="/";this.linkHidden=false;this.getPanel=function(){return _29c;};this.setName=function(name){_29d=name;};this.getName=function(){return _29d;};this.setDelim=function(_2a2){_2a0=_2a2;};this.getDelim=function(){return _2a0;};this.setParentPane=function(_2a3){if(_2a3&&_2a3.getCompositeToken){_29e=_2a3;_29c._a_onParentPaneSet();}};this.getParentPane=function(){return _29e;};this.isRootPane=function(){return _29e==null;};this._a_onParentPaneSet=function(){};this.getDepth=function(){return _29e?_29e.getDepth()+1:0;};this.setToken=function(_2a4){_29f=_2a4;};this.getToken=function(){return _29f;};this.getCompositeToken=function(_2a5){if(_2a5){return _29e?[_29e.getCompositeToken(_29f),_2a0,_2a5].join(""):[_29f,_2a5].join(_2a0);}
return _29e?_29e.getCompositeToken(_29f):_29f;};this.activate=function(_2a6){return true;};this.passivate=function(_2a7){return true;};this.init=function(){};this.reset=function(){};function construct(){}
construct();}
function AbstractTreePane(){var _2a8=this;this.__extends=AbstractPane;this.__extends();var _2a9=null;var _2aa=new IndexedMap();var _2ab=true;var _2ac=true;this.setIndented=function(_2ad){_2ac=_2ad;};this.isIndented=function(){return _2ac;};this.isExpanded=function(){return _2ab;};function expandOrCollapse(_2ae,_2af){for(var i=0;i<_2ae.length;i++){var p=_2ae[i];p.setVisible(_2af);if(p.props.panes){expandOrCollapse(p.props.panes,_2af);}}}
this.collapsePanes=function(){_2ab=false;expandOrCollapse(_2a8.props.panes,_2ab);};this.expandPanes=function(){_2ab=true;expandOrCollapse(_2a8.props.panes,_2ab);};this.toggleTree=function(){_2ab=!_2ab;expandOrCollapse(_2a8.props.panes,_2ab);};this.setDefaultLinkStyle=function(_2b2){_2a9=_2b2;};this.getDefaultLinkStyle=function(){if(!_2a9){var _2b3=_2a8.getParentPane();_2a9=_2b3?_2b3.getDefaultLinkStyle():null;}
return _2a9;};this.newLink=function(_2b4,_2b5){return WidgetFactory.create("a",_2b4,_2b5);};this.newPane=function(_2b6){return new FlowPanel(_2b6);};this.newEntryPane=function(_2b7,p,_2b9){return _2b9?_2a8.addEntry(WidgetFactory.create("a",_2b7,_2b9.k),new FlowPanel(_2b9.v),p):_2a8.addEntry(_2b7,new FlowPanel(),p);};this.addTreePane=function(pane){this.addEntry(pane.getName(),pane);};this.addEntry=function(_2bb,pane,p){var link=Utils.isString(_2bb)?_2a8.newLink(_2bb):_2bb;var _2bf=Utils.isWidget(p)?(p.props.tree==_2a8?p:_2a8):_2a8;if(_2ac){pane.setStyleProperty("margin","2px 0 2px 10px");}
link.addEventHandler("onclick",function(e){pane.toggle();});_2bf.addChild(new SimplePanel(link));_2bf.addChild(pane);if(pane.getDepth){pane.setParentPane(_2bf);if(_2a8.equals(_2bf)){_2aa.put(pane.getToken(),pane);}}
link.addStyle(_2a8.getDefaultLinkStyle());pane.props.tree=_2a8;if(!_2bf.props.panes){_2bf.props.panes=new Array();}
_2bf.props.panes.push(pane);return pane;};this.init=function(){if(_2a8.isRootPane()){_2a8.collapsePanes(_2a8.props.panes);}
var map=_2aa.__wrappedGet();for(var i in map){map[i].init();}};this.activate=function(_2c3){_2a8.setVisible(true);var sub=_2a8.getDepth()+1;if(sub==_2c3.length){return;}
var pane=_2aa.get(_2c3[sub]);if(pane){pane.activate(_2c3);}
return true;};this.passivate=function(_2c6){return true;};function construct(){_2a8.props.panes=new Array();}
construct();}