
var Utils={isBoolean:function(_1){return typeof _1=="boolean";},isNumber:function(_2){return typeof _2=="number";},isString:function(_3){return typeof _3=="string";},isArray:function(_4){return _4&&!Utils.isString(_4)?Utils.isNumber(_4.length):false;},isNode:function(_5){return _5&&_5.nodeName;},isWidget:function(_6){return _6&&_6.getElement;},isDraggable:function(el){return el&&el.__drag;},applyStyle:function(el,_9){if(document.all&&!window.opera){el.style.setAttribute("cssText",_9);}else{el.setAttribute("style",_9);}},getCssStyle:function(el,_b){if(el.currentStyle){return el.currentStyle[_b];}else{if(window.getComputedStyle){return window.getComputedStyle(el,"").getPropertyValue(_b);}}
return null;},getStyleProperty:function(el,_d){var p=el.style[_d];return p?p:Utils.getCssStyle(el,_d);},getZIndex:function(el){return el.style.zIndex?el.style.zIndex:(document.all?Utils.getCssStyle(el,"zIndex"):Utils.getCssStyle(el,"z-index"));},refreshElement:function(el){while(el.hasChildNodes()){el.removeChild(el.firstChild);}},trim:function(str){return str.replace(/^\s+/g,"").replace(/\s+$/g,"");},trimLineBreaks:function(str){return str.replace(/(\r\n|[\r\n])/g," ");},getName:function(el){return el.name?el.name:el.getAttribute("name");},getParentName:function(el){var p=el.parentNode;if(!p){return null;}
var _16=p.name?p.name:p.getAttribute("name");return _16?_16:Utils.getParentName(p);},addHandlerToEvent:function(_17,el,ev){if(el.addEventListener){el.addEventListener(ev.substring(2),_17,false);}else{if(el.attachEvent){el.attachEvent(ev,_17);}else{var _1a=el[ev];el[ev]=function(e){_1a(e);_17(e);};}}},addOnLoad:function(_1c){var _1d=window.onload;window.onload=function(){if(typeof _1d=="function"){_1d();}
_1c();};},addOnUnload:function(_1e){var _1f=window.onunload;window.onunload=function(){if(typeof _1f=="function"){_1f();}
_1e();};},getEventSource:function(ev){if(!ev){ev=window.event;}
return ev.target?ev.target:ev.srcElement;},toggle:function(el){if(!el.style.display||el.style.display!="none"){el.style.display="none";}else{el.style.display="block";}},hideFirstChild:function(_22){if(_22&&_22.firstChild){_22.firstChild.style.display="none";}},hideLastChild:function(_23){if(_23&&_23.lastChild){_23.lastChild.style.display="none";}},getEventCoords:function(ev){var x=0;var y=0;if(document.all){x=document.documentElement.scrollLeft||document.body.scrollLeft;y=document.documentElement.scrollTop||document.body.scrollTop;x+=window.event.clientX;y+=window.event.clientY;}else{x=ev.pageX;y=ev.pageY;}
return{x:x,y:y};},getLeft:function(el){var _28=0;for(;;){if(!el.offsetParent){_28+=el.offsetLeft;break;}
_28+=(el.offsetLeft-el.scrollLeft);el=el.offsetParent;}
return _28;},getTop:function(el){var top=0;for(;;){if(!el.offsetParent){top+=el.offsetTop;break;}
top+=(el.offsetTop-el.scrollTop);el=el.offsetParent;}
return top;},getCoords:function(el){var _2c=0;var top=0;for(;;){if(!el.offsetParent){_2c+=el.offsetLeft;top+=el.offsetTop;break;}
_2c+=(el.offsetLeft-el.scrollLeft);top+=(el.offsetTop-el.scrollTop);el=el.offsetParent;}
return{x:_2c,y:top};},getCenterCoords:function(){var _2e=document.documentElement.scrollLeft||document.body.scrollLeft;var _2f=document.documentElement.scrollTop||document.body.scrollTop;var _30=document.body.clientWidth/2+_2e;var top=document.body.clientHeight/2+_2f;return{x:_30,y:top};},positionCenter:function(el){var _33=(document.body.clientWidth-el.offsetWidth)/2;var top=(document.body.clientHeight-el.offsetHeight)/2;var _35=document.documentElement.scrollLeft||document.body.scrollLeft;var _36=document.documentElement.scrollTop||document.body.scrollTop;el.style.left=[_35+_33,"px"].join("");el.style.top=[_36+top,"px"].join("");},newXHR:function(){return window.XMLHttpRequest?new XMLHttpRequest():new ActiveXObject("Microsoft.XMLHTTP");},_script_counter:0,findParentByNodeName:function(el,_38){return el.nodeName==_38?el:el.parentNode?Utils.findParentByNodeName(el.parentNode,_38):null;},deleteCookie:function(_39){document.cookie=[_39,"=","; expires=Thu, 01-Jan-70 00:00:01 GMT"].join("");},getCookie:function(_3a){var c=document.cookie.split(";");for(var i=0;i<c.length;i++){var t=Utils.trim(c[i]);if(t.substring(0,_3a.length)==_3a){return t.substring(_3a.length+1,t.length);}}
return null;},createCookie:function(_3e,_3f,_40){var _41=Utils.isNumber(_40)?new Date((1000*_40)+new Date().getTime()).toGMTString():"";document.cookie=[_3e,"=",_3f,"; expires=",_41].join("");},validateForm:function(_42,_43,_44){if(_44){return Utils.validateFormResolveName(_42,_43);}
for(var i=0;i<_42.elements.length;i++){var _46=_42.elements[i];if("true"!=_46.getAttribute("required")){continue;}
if(_46.type.toLowerCase()=="text"){_46.value=Utils.trim(_46.value);if(_46.value.length<1){var _47=Utils.getName(_46);var msg=["Required field: ",_47.substring(0,1).toUpperCase(),_47.substring(1)].join("");if(Utils.isNode(_43)){_43.innerHTML=msg;}else{alert(msg);}
_46.focus();return false;}}else{if(_46.type.toLowerCase()=="textarea"){var ta=_46;ta.value=Utils.trimLineBreaks(ta.value);ta.value=Utils.trim(ta.value);if(ta.value.length<1){var _47=Utils.getName(ta);var msg=["Required field: ",_47.substring(0,1).toUpperCase(),_47.substring(1)].join("");if(Utils.isNode(_43)){_43.innerHTML=msg;}else{alert(msg);}
return false;}}else{if(_46.nodeName.toLowerCase()=="select"){var sel=_46;if(sel.value.length<1){var _47=Utils.getName(sel);var msg=["Required field: ",_47.substring(0,1).toUpperCase(),_47.substring(1)].join("");if(Utils.isNode(_43)){_43.innerHTML=msg;}else{alert(msg);}
return false;}}else{if(_46.type.toLowerCase()=="password"){var _4b=_46;var _4c=_4b.value.length;var _4d=Utils.trim(_4b.value).length;if(_4c==0){var _47=Utils.getName(_4b);var msg=["Required field: ",_47.substring(0,1).toUpperCase(),_47.substring(1)].join("");if(Utils.isNode(_43)){_43.innerHTML=msg;}else{alert(msg);}
_4b.focus();_4b.select();return false;}
if(_4c!=_4d){var msg="Your password must not contain any whitespace.";if(Utils.isNode(_43)){_43.innerHTML=msg;}else{alert(msg);}
_4b.focus();_4b.select();return false;}}}}}}
return true;},validateFormResolveName:function(_4e,_4f){for(var i=0;i<_4e.elements.length;i++){var _51=_4e.elements[i];if("true"!=_51.getAttribute("required")){continue;}
if(_51.type.toLowerCase()=="text"){_51.value=Utils.trim(_51.value);if(_51.value.length<1){var msg=["Required field: ",Utils.getParentName(_51)].join("");if(Utils.isNode(_4f)){_4f.innerHTML=msg;}else{alert(msg);}
_51.focus();return false;}}else{if(_51.type.toLowerCase()=="textarea"){var ta=_51;ta.value=Utils.trimLineBreaks(ta.value);ta.value=Utils.trim(ta.value);if(ta.value.length<1){var msg=["Required field: ",Utils.getParentName(ta)].join("");if(Utils.isNode(_4f)){_4f.innerHTML=msg;}else{alert(msg);}
return false;}}else{if(_51.nodeName.toLowerCase()=="select"){var sel=_51;if(sel.value.length<1){var msg=["Required field: ",Utils.getParentName(sel)].join("");if(Utils.isNode(_4f)){_4f.innerHTML=msg;}else{alert(msg);}
return false;}}else{if(_51.type.toLowerCase()=="password"){var _55=_51;var _56=_55.value.length;var _57=Utils.trim(_55.value).length;if(_56==0){var msg=["Required field: ",Utils.getParentName(_55)].join("");if(Utils.isNode(_4f)){_4f.innerHTML=msg;}else{alert(msg);}
_55.focus();_55.select();return false;}
if(_56!=_57){var msg="Your password must not contain any whitespace.";if(Utils.isNode(_4f)){_4f.innerHTML=msg;}else{alert(msg);}
_55.focus();_55.select();return false;}}}}}}
return true;}};var History={handlers:new Array(),currentToken:window.location.hash,loopKey:null,back:function(){if(window.history.length){window.history.back();}},newItem:function(_58){if(_58!=History.currentToken){window.location.hash=_58;}},onHistoryChanged:function(_59){var h=History.handlers;for(var i in h){h[i](_59);}},getToken:function(){return History.currentToken;},addHandler:function(_5c){var idx=History.handlers.indexOf(_5c);if(idx==-1){History.handlers.push(_5c);}},loop:function(){var _5e=window.location.hash.substring(1);if(_5e!=History.currentToken){History.currentToken=_5e;History.onHistoryChanged(_5e);}},stop:function(){if(History.loopKey){window.clearInterval(History.loopKey);History.loopKey=null;}},isStarted:function(){return History.loopKey!=null;},start:function(){if(!History.loopKey){History.loopKey=window.setInterval(History.loop,250);}}};if(!Array.prototype.indexOf){Array.prototype.indexOf=function(elt){var len=this.length;var _61=Number(arguments[1])||0;_61=(_61<0)?Math.ceil(_61):Math.floor(_61);if(_61<0){_61+=len;}
for(;_61<len;_61++){if(_61 in this&&this[_61]===elt){return _61;}}
return-1;};}
function JSObject(){var _62=this;this.equals=function(obj){return _62==obj;};function construct(){}
construct();}
function Indexed(){var _64=this;this.__extends=JSObject;this.__extends();var _65=-1;this.setIndex=function(_66){_65=_66;};this.getIndex=function(){return _65;};function construct(){}
construct();}
function AbstractCollection(){var _67=this;this.__extends=JSObject;this.__extends();this.isEmpty=function(){};this.clear=function(){};this.size=function(){};this.get=function(obj){};this.remove=function(obj){};function construct(){}
construct();}
function ArrayList(){var _6a=this;this.__extends=AbstractCollection;this.__extends();var _6b=new Array();this.add=function(obj){if(obj){var idx=_6b.length;_6b.push(obj);_6a._a_onAdd(obj,idx,idx+1);}};this.remove=function(_6e){if(Utils.isNumber(_6e)){return _6e<_6b.length?_6b.splice(_6e,1)[0]:null;}else{if(_6e&&_6e.equals){for(var i in _6b){if(_6b[i].equals(_6e)){var _70=_6b.splice(i,1)[0];_6a._a_onRemove(_70,i,_6b.length);return _70;}}}}
return null;};this.get=function(_71){return _71<_6b.length?_6b[_71]:null;};this.indexOf=function(obj){if(obj){for(var i in _6b){if(_6b[i].equals(obj)){return i;}}}
return-1;};this.contains=function(obj){return _6a.indexOf(obj)!=-1;};this.size=function(){return _6b.length;};this.clear=function(){_6b.splice(0,_6b.length);};this.isEmpty=function(){return _6b.length==0;};this.__wrappedGet=function(){return _6b;};this._a_onAdd=function(obj,_76,_77){};this._a_onRemove=function(obj,_79,_7a){};function construct(){}
construct();}
function IndexedList(_7b){var _7c=this;this.__extends=ArrayList;this.__extends();var _7d=Utils.isBoolean(_7b)?_7b:true;var _7e=this.add;this.add=function(obj){if(obj){if(!obj.setIndex){obj.setIndex=function(idx){obj.__index=idx;};obj.getIndex=function(){return obj.__index;};}
_7e(obj);}};this._a_onAdd=function(obj,_82,_83){obj.setIndex(_82);};function reflectRemoval(_84,_85){var _86=_7c.__wrappedGet();for(var i=_84;i<_85;i++){_86[i].setIndex(i);}}
this._a_onRemove=function(obj,_89,_8a){if(_7d){reflectRemoval(_89,_8a);}};function construct(){}
construct();}
function HashMap(){var _8b=this;this.__extends=AbstractCollection;this.__extends();var _8c={};var _8d=0;this.put=function(key,_8f){if(key&&_8f){_8c[key]=_8f;_8b._a_onPut(key,_8f,++_8d);}};this.get=function(key){return key?_8c[key]:null;};this.remove=function(key){if(key){var _92=_8c[key];_8c[key]=null;_8b._a_onRemove(key,_92,--_8d);return _92;}
return null;};this.size=function(){return _8d;};this.clear=function(){_8c={};_8d=0;};this.isEmpty=function(){return _8d==0;};this.__wrappedGet=function(){return _8c;};this._a_onPut=function(key,_94,_95){};this._a_onRemove=function(key,_97,_98){};function construct(){}
construct();}
function IndexedMap(_99){var _9a=this;this.__extends=HashMap;this.__extends();var _9b=Utils.isBoolean(_99)?_99:true;var _9c=this.put;this.put=function(key,_9e){if(_9e){if(!_9e.setIndex){_9e.setIndex=function(idx){_9e.__index=idx;};_9e.getIndex=function(){return _9e.__index;};}
_9c(key,_9e);}};this._a_onPut=function(key,_a1,_a2){_a1.setIndex(_a2-1);};function reflectRemoval(_a3,_a4){var map=_9a.__wrappedGet();var _a6=_a3.getIndex();for(var i in map){var v=map[i];if(v&&v.getIndex()>_a6){v.setIndex(v.getIndex()-1);}}}
this._a_onRemove=function(key,_aa,_ab){if(_9b){reflectRemoval(_aa,_ab);}};function construct(){}
construct();}
function PooledRequest(pl){var _ad=this;this.__extends=JSObject;this.__extends();var _ae=pl;var _af=Utils.newXHR();var _b0=null;this.handle=function(_b1){var _b2=_b0;_b0=null;_ae.push(_ad);_b2(_b1);};this.eval=function(_b3){_ad.handle(window.eval(["(",_b3,")"].join("")));};function handleDefault(){if(_af.readyState==4){if(_af.status==200){_ad.eval(_af.responseText);}}}
this.sendCachable=function(url,_b5,_b6,_b7){_b0=_b6;_af.open(_b7,url,true);_af.onreadystatechange=handleDefault;_af.send(null);};this.send=function(url,_b9,_ba,_bb){_b0=_ba;_af.open(_bb,url,true);_af.onreadystatechange=handleDefault;_af.setRequestHeader("Content-Type","application/x-www-form-urlencoded");_af.setRequestHeader("Content-Length",_b9.length);_af.send(_b9);};this.doGet=function(url,_bd,_be){_ad.sendCachable(url,_bd,_be,"GET");};this.doDelete=function(url,_c0,_c1){_ad.sendCachable(url,_c0,_c1,"DELETE");};this.doPost=function(url,_c3,_c4){_ad.send(url,_c3,_c4,"POST");};this.doPut=function(url,_c6,_c7){_ad.send(url,_c6,_c7,"PUT");};this.getRequest=function(){return _af;};function construct(){}
construct();}
function RequestPool(_c8){var _c9=this;this.__extends=JSObject;this.__extends();var _ca=new Array();this.push=function(req){_ca.push(req);};this.addNew=function(){_ca.push(new PooledRequest(_c9));};this.send=function(url,_cd,_ce){_ca.shift().send(url,_cd,_ce,"POST");};this.doPut=function(url,_d0,_d1){_ca.shift().doPut(url,_d0,_d1);};this.doPost=function(url,_d3,_d4){_ca.shift().doPost(url,_d3,_d4);};this.doGet=function(url,_d6,_d7){_ca.shift().doGet(url,_d6,_d7);};this.doDelete=function(url,_d9,_da){_ca.shift().doDelete(url,_d9,_da);};function construct(_db){var len=_db?_db:4;for(var i=0;i<len;i++){_ca.push(new PooledRequest(_c9));}}
construct(_c8);}
function IFrameRequest(){var _de=this;this.__extends=JSObject;this.__extends();var _df=null;function scheduleRemove(){_df.removeChild(_df.firstChild);}
function cleanIFrameDiv(e,_e1){var _e2=null;if(e.currentTarget){_e2=e.currentTarget.contentDocument.body.firstChild.innerHTML;}else{if(e.srcElement){_e2=e.srcElement.contentWindow.document.body.firstChild.innerHTML;}}
if(_e1){_e1(window.eval(["(",_e2,")"].join("")));}}
this.send=function(url,_e4,_e5){var _e6=url.indexOf("?")==-1?"?":"&";var ifr=document.createElement("iframe");Utils.addHandlerToEvent(function(e){cleanIFrameDiv(e,_e5);},ifr,"onload");Utils.applyStyle(ifr,"display:none");ifr.src=[url,_e6,_e4].join("");_df.appendChild(ifr);};function construct(){_df=document.createElement("div");Utils.applyStyle(_df,"display:none");document.body.appendChild(_df);}
construct();}
function ScriptRequest(){var _e9=this;this.__extends=JSObject;this.__extends();var _ea=null;var _eb=["scr",Utils._script_counter++].join("");var _ec=new Array();this.handle=function(_ed){var _ee=_ec.shift();if(_ee){_ee(_ed);}};this.send=function(url,_f0,_f1){var _f2=url.indexOf("?")==-1?["?callback=",_eb,".handle&"].join(""):["&callback=",_eb,".handle&"].join("");var scr=document.createElement("script");Utils.applyStyle(scr,"display:none");_ec.push(_f1);scr.src=[url,_f2,_f0].join("");_ea.appendChild(scr);};function construct(){window[_eb]=_e9;_ea=document.createElement("div");Utils.applyStyle(_ea,"display:none");document.body.appendChild(_ea);}
construct();}
function CometdClient(u,obj,_f6){var _f7=this;this.__extends=JSObject;this.__extends();var _f8=u.length-1==u.lastIndexOf("/")?u.substring(0,u.length-1):u;var _f9=obj;var _fa=null;var _fb={};var _fc=false;var _fd=false;var _fe=null;var _id=null;function handle(msgs){if(msgs){if(_fd){_fa.send(_f8,"action=reconnect",handle);}else{_fc=false;}
if(Utils.isArray(msgs)){for(var i in msgs){var m=msgs[i];var cb=_fb[m.channel];if(cb){if(_f9&&Utils.isString(cb)){_f9[cb](m);}else{cb(m);}}}}}}
function onConnect(c){_id=c.id;for(var i in c.channels){_fb[c.channels[i]]="tmp";}
_fc=true;if(Utils.isString(_fe)){_f9[_fe]();}else{if(_fe){_fe();}}
_fa.send(_f8,"action=reconnect",handle);}
this.isConnected=function(){return _fc;};this.getId=function(){return _id;};this.start=function(_106){if(!_fc){_fe=_106;_fa.send(_f8,"action=connect",onConnect);}
_fd=true;};this.stop=function(_107){if(_fc){_fc=false;_fa.send(_f8,"action=disconnect",_107?_107:function(){});}
_fd=false;};this.publish=function(_108,data){if(_fc){if(_108.lastIndexOf("/")==_108.length-1){_108=_108.substring(0,_108.length-1);}
var ch=_fb[_108];if(ch){_fa.send(_f8+_108+"?action=publish",data,handle);}}};this.subscribe=function(_10b,_10c){if(_fc){if(_10b.lastIndexOf("/")==_10b.length-1){_10b=_10b.substring(0,_10b.length-1);}
var old=_fb[_10b];_fb[_10b]=_10c;if(!old){_fa.send(_f8+_10b,"action=subscribe",handle);}}};this.unsubscribe=function(_10e){if(_fc){if(_10e.lastIndexOf("/")==_10e.length-1){_10e=_10e.substring(0,_10e.length-1);}
var ch=_fb[_10e];if(ch){chanels[_10e]=null;_fa.send(_f8+_10e,"action=unsubscribe",handle);}}};function construct(u,obj,type){if(type){if(type=="iframe"){_fa=new IFrameRequest();}else{if(type=="script"){_fa=new ScriptRequest();}else{if(type=="xhr"){_fa=new RequestPool(5);}}}}
if(!_fa){_fa=new RequestPool(5);}}
construct(u,obj,_f6);}
var DragUtil={getInitialLeft:function(el){if(el.style.left){return parseInt(el.style.left);}
var left=Utils.getCssStyle(el,"left");var idx=left.indexOf("px");return idx==-1?0:parseInt(left.substring(0,idx));},getInitialTop:function(el){if(el.style.top){return parseInt(el.style.top);}
var top=Utils.getCssStyle(el,"top");var idx=top.indexOf("px");return idx==-1?0:parseInt(top.substring(0,idx));},_draggables:new HashMap(),_dropabbles:new HashMap(),addDrag:function(el,drag){DragUtil._draggables.put(el,drag);},addDragDrop:function(el,_11c){DragUtil._droppables.put(el,_11c);},_front:null,bringToFront:function(_11d){if(Utils.isNode(_11d)){_11d=_11d.__drag;}
if(_11d&&_11d.bringToFront){if(DragUtil._front){DragUtil._front.bringToBack();}
DragUtil._front=_11d;_11d.bringToFront();}}};function Draggable(el,_11f){var _120=this;this.__extends=JSObject;this.__extends();var _el=null;var _122=0;var _123=0;var _124=null;var _125=null;var _126=null;var _127=null;this.getElement=function(){return _el;};this.bringToFront=function(){_el.style.zIndex=10000;};this.bringToBack=function(){_el.style.zIndex=_124;};this.reset=function(){if(_127){if(_126!="absolute"&&_126!="fixed"){_el.style.left=[_127.relX,"px"].join("");_el.style.top=[_127.relY,"px"].join("");}else{_el.style.left=[_127.initX,"px"].join("");_el.style.top=[_127.initY,"px"].join("");}}};function mouseMove(e){if(!e){e=window.event;}
_el.style.left=[_122+e.clientX,"px"].join("");_el.style.top=[_123+e.clientY,"px"].join("");}
function mouseUp(e){document.onmousemove=null;document.onselectstart=null;document.onmouseup=null;}
function mouseDown(e){if(!e){e=window.event;}
var el=e.target?e.target:e.srcElement;if(el!=_125){if(el==_el){DragUtil.bringToFront(_120);}
return;}
if(_126!="absolute"&&_126!="fixed"){if(!_127){_127=Utils.getCoords(_el);_127.relX=DragUtil.getInitialLeft(_el);_127.relY=DragUtil.getInitialTop(_el);_122=_127.relX-e.clientX;_123=_127.relY-e.clientY;}else{var _12c=_el.style.left?parseInt(_el.style.left):0;var _12d=_el.style.top?parseInt(_el.style.top):0;_122=_12c-e.clientX;_123=_12d-e.clientY;}}else{if(!_127){_127=Utils.getCoords(_el);_127.initX=DragUtil.getInitialLeft(_el);_127.initY=DragUtil.getInitialTop(_el);}
_122=_el.offsetLeft-e.clientX;_123=_el.offsetTop-e.clientY;}
DragUtil.bringToFront(_120);document.onmouseup=mouseUp;document.onmousemove=mouseMove;document.body.focus();document.onselectstart=function(){return false;};return false;}
function construct(el,_12f){_el=el;_el.onmousedown=mouseDown;_el.style.cursor="default";_124=Utils.getZIndex(_el);_125=_12f;if(_125){_125.style.cursor="default";}else{_125=_el;}
_126=_el.style.position?_el.style.position:Utils.getCssStyle(_el,"position");if(_126!="absolute"&&_126!="fixed"){_el.style.position="relative";}
_el.__drag=_120;DragUtil.addDrag(_el,_120);}
construct(el,_11f);}
function DraggableBounded(el,_131,_132){var _133=this;this.__extends=JSObject;this.__extends();var _el=null;var _135=0;var _136=0;var _137=null;var _138=null;var _139=null;var _13a=null;var _13b=null;var _13c=null;var _13d=null;this.getElement=function(){return _el;};this.bringToFront=function(){_el.style.zIndex=10000;};this.bringToBack=function(){_el.style.zIndex=_137;};this.reset=function(){if(_13a){if(_139!="absolute"&&_139!="fixed"){_el.style.left=[_13a.relX,"px"].join("");_el.style.top=[_13a.relY,"px"].join("");}else{_el.style.left=[_13a.initX,"px"].join("");_el.style.top=[_13a.initY,"px"].join("");}}};function mouseMove(e){if(!e){e=window.event;}
var x=_135+e.clientX+_13a.x-_13a.relX+_13d.x;var y=_136+e.clientY+_13a.y-_13a.relY+_13d.y;if(_13c.xa<x+1&&_13c.ya<y+1&&_13c.xb>x-1+_el.offsetWidth&&_13c.yb>y-1+_el.offsetHeight){_el.style.left=[_135+e.clientX,"px"].join("");_el.style.top=[_136+e.clientY,"px"].join("");}}
function mouseUp(e){document.onmousemove=null;document.onselectstart=null;document.onmouseup=null;}
function mouseDown(e){if(!e){e=window.event;}
var el=e.target?e.target:e.srcElement;if(el!=_138){if(el==_el){DragUtil.bringToFront(_133);}
return;}
if(_139!="absolute"&&_139!="fixed"){if(!_13a){_13d={x:0,y:0};_13a=Utils.getCoords(_el);_13a.relX=DragUtil.getInitialLeft(_el);_13a.relY=DragUtil.getInitialTop(_el);if(_13b==document.body){_parentCoords={x:0,y:0,relX:0,relY:0};_13c={xa:_parentCoords.x,xb:_parentCoords.x+document.body.clientWidth,ya:_parentCoords.y,yb:document.body.clientHeight};}else{_parentCoords=Utils.getCoords(_13b);_parentCoords.relX=0;_parentCoords.relY=0;_13c={xa:_parentCoords.x,xb:_parentCoords.x+_13b.offsetWidth,ya:_parentCoords.y,yb:_parentCoords.y+_13b.offsetHeight};}
_135=_13a.relX-e.clientX;_136=_13a.relY-e.clientY;}else{var _144=_el.style.left?parseInt(_el.style.left):0;var _145=_el.style.top?parseInt(_el.style.top):0;_135=_144-e.clientX;_136=_145-e.clientY;}}else{if(!_13a){_13a=Utils.getCoords(_el);_13a.initX=DragUtil.getInitialLeft(_el);_13a.initY=DragUtil.getInitialTop(_el);if(_13b==document.body){_parentCoords={x:0,y:0,relX:0,relY:0};_13d={x:0,y:0};_13c={xa:_parentCoords.x,xb:_parentCoords.x+document.body.clientWidth,ya:_parentCoords.y,yb:document.body.clientHeight};}else{_parentCoords=Utils.getCoords(_13b);_parentCoords.relX=DragUtil.getInitialLeft(_13b);_parentCoords.relY=DragUtil.getInitialTop(_13b);var pos=_13b.style.position?_13b.style.position:Utils.getCssStyle(_13b,"position");if(pos=="static"){_13d={x:0,y:0};}else{_13d=_parentCoords;}
_13c={xa:_parentCoords.x,xb:_parentCoords.x+_13b.offsetWidth,ya:_parentCoords.y,yb:_parentCoords.y+_13b.offsetHeight};}}
_135=_el.offsetLeft-e.clientX;_136=_el.offsetTop-e.clientY;}
DragUtil.bringToFront(_133);document.onmouseup=mouseUp;document.onmousemove=mouseMove;document.body.focus();document.onselectstart=function(){return false;};return false;}
function construct(el,_148,_149){_el=el;_el.onmousedown=mouseDown;_el.style.cursor="default";_137=Utils.getZIndex(_el);_138=_148;if(_138){_138.style.cursor="default";}else{_138=_el;}
_139=_el.style.position?_el.style.position:Utils.getCssStyle(_el,"position");if(_139!="absolute"&&_139!="fixed"){_el.style.position="relative";}
_13b=Utils.isNode(_149)?_149:_el.parentNode;_el.__drag=_133;DragUtil.addDrag(_el,_133);}
construct(el,_131,_132);}
function DraggableProxy(el,_14b,_14c,_14d,_14e){var _14f=this;this.__extends=JSObject;this.__extends();var _el=null;var _151=0;var _152=0;var _153=null;var _154=null;var _155=null;var _156=null;var _157=null;var _158=true;var _159=true;this.getElement=function(){return _el;};this.bringToFront=function(){_el.style.zIndex=10000;};this.bringToBack=function(){_el.style.zIndex=_153;};this.setResizeProxy=function(_15a){_158=_15a;};this.isResizeProxy=function(){return _158;};this.setMoveOriginal=function(_15b){_159=_15b;};this.isMoveOriginal=function(){return _159;};this.reset=function(){if(_156){if(_155!="absolute"&&_155!="fixed"){_el.style.left=[_156.relX,"px"].join("");_el.style.top=[_156.relY,"px"].join("");}else{_el.style.left=[_156.initX,"px"].join("");_el.style.top=[_156.initY,"px"].join("");}}};function mouseMove(e){if(!e){e=window.event;}
_157.style.display="";_157.style.left=[_151+e.clientX+_156.x-_156.relX,"px"].join("");_157.style.top=[_152+e.clientY+_156.y-_156.relY,"px"].join("");}
function mouseUp(e){document.onmousemove=null;document.onselectstart=null;document.onmouseup=null;if(_159){var x=parseInt(_157.style.left);var y=parseInt(_157.style.top);_el.style.left=[x-_156.x+_156.relX,"px"].join("");_el.style.top=[y-_156.y+_156.relY,"px"].join("");}
_157.style.zIndex=null;_157.style.display="none";}
function mouseDown(e){if(!e){e=window.event;}
var el=e.target?e.target:e.srcElement;if(el!=_154){if(el==_el){DragUtil.bringToFront(_14f);}
return;}
if(_155!="absolute"&&_155!="fixed"){if(!_156){_156=Utils.getCoords(_el);_156.relX=DragUtil.getInitialLeft(_el);_156.relY=DragUtil.getInitialTop(_el);_151=_156.relX-e.clientX;_152=_156.relY-e.clientY;}else{var _162=_el.style.left?parseInt(_el.style.left):0;var _163=_el.style.top?parseInt(_el.style.top):0;_151=_162-e.clientX;_152=_163-e.clientY;}}else{if(!_156){_156={x:0,y:0,relX:0,relY:0};_156.initX=DragUtil.getInitialLeft(_el);_156.initY=DragUtil.getInitialTop(_el);}
_151=_el.offsetLeft-e.clientX;_152=_el.offsetTop-e.clientY;}
_153=_el.style.zIndex;if(_158){_157.style.width=[_el.offsetWidth,"px"].join("");_157.style.height=[_el.offsetHeight,"px"].join("");}
DragUtil.bringToFront(_14f);_157.style.zIndex=10000;document.onmouseup=mouseUp;document.onmousemove=mouseMove;document.body.focus();document.onselectstart=function(){return false;};return false;}
function construct(el,_165,_166,_167,_168){_el=el;_el.onmousedown=mouseDown;_el.style.cursor="default";_153=Utils.getZIndex(_el);_154=_165;if(_154){_154.style.cursor="default";}else{_154=_el;}
_155=_el.style.position?_el.style.position:Utils.getCssStyle(_el,"position");if(_155!="absolute"&&_155!="fixed"){_el.style.position="relative";}
_157=document.createElement("div");if(_166){_157.className=_166;}
_157.style.position="absolute";_157.style.display="none";document.body.appendChild(_157);if(Utils.isBoolean(_168)){_158=_168;}
if(Utils.isBoolean(_167)){_159=_167;}
_el.__drag=_14f;DragUtil.addDrag(_el,_14f);}
construct(el,_14b,_14c,_14d,_14e);}
function DraggableProxyBounded(el,_16a,_16b,_16c,_16d,_16e){var _16f=this;this.__extends=JSObject;this.__extends();var _el=null;var _171=0;var _172=0;var _173=null;var _174=null;var _175=null;var _176=null;var _177=null;var _178=null;var _179=null;var _17a=null;var _17b=true;var _17c=true;var _17d=null;this.getElement=function(){return _el;};this.bringToFront=function(){_el.style.zIndex=10000;};this.bringToBack=function(){_el.style.zIndex=_173;};this.setResizeProxy=function(_17e){_17b=_17e;};this.isResizeProxy=function(){return _17b;};this.setMoveOriginal=function(_17f){_17c=_17f;};this.isMoveOriginal=function(){return _17c;};this.setContainer=function(_180){if(Utils.isNode(_180)){_17d=_180;}};this.getContainer=function(){return _17d;};this.reset=function(){if(_176){if(_175!="absolute"&&_175!="fixed"){_el.style.left=[_176.relX,"px"].join("");_el.style.top=[_176.relY,"px"].join("");}else{_el.style.left=[_176.initX,"px"].join("");_el.style.top=[_176.initY,"px"].join("");}}};function mouseMove(e){if(!e){e=window.event;}
_177.style.display="";var x=_171+e.clientX+_176.x-_176.relX+_17a.x;var y=_172+e.clientY+_176.y-_176.relY+_17a.y;if(_179.xa<x+1&&_179.ya<y+1&&_179.xb>x-1+_el.offsetWidth&&_179.yb>y-1+_el.offsetHeight){_177.style.left=[x,"px"].join("");_177.style.top=[y,"px"].join("");}}
function mouseUp(e){document.onmousemove=null;document.onselectstart=null;document.onmouseup=null;if(_17c){var x=parseInt(_177.style.left);var y=parseInt(_177.style.top);_el.style.left=[x-_176.x+_176.relX-_17a.x,"px"].join("");_el.style.top=[y-_176.y+_176.relY-_17a.y,"px"].join("");}
_177.style.zIndex=null;_177.style.display="none";}
function mouseDown(e){if(!e){e=window.event;}
var el=e.target?e.target:e.srcElement;if(el!=_174){if(el==_el){DragUtil.bringToFront(_16f);}
return;}
if(_175!="absolute"&&_175!="fixed"){if(!_176){_17a={x:0,y:0};_176=Utils.getCoords(_el);_176.relX=DragUtil.getInitialLeft(_el);_176.relY=DragUtil.getInitialTop(_el);if(_17d==document.body){_178={x:0,y:0,relX:0,relY:0};_179={xa:_178.x,xb:_178.x+document.body.clientWidth,ya:_178.y,yb:document.body.clientHeight};}else{_178=Utils.getCoords(_17d);_178.relX=0;_178.relY=0;_179={xa:_178.x,xb:_178.x+_17d.offsetWidth,ya:_178.y,yb:_178.y+_17d.offsetHeight};}
_171=_176.relX-e.clientX;_172=_176.relY-e.clientY;}else{var _189=_el.style.left?parseInt(_el.style.left):0;var _18a=_el.style.top?parseInt(_el.style.top):0;_171=_189-e.clientX;_172=_18a-e.clientY;}}else{if(!_176){_176={x:0,y:0,relX:0,relY:0};_176.initX=DragUtil.getInitialLeft(_el);_176.initY=DragUtil.getInitialTop(_el);if(_17d==document.body){_178={x:0,y:0,relX:0,relY:0};_17a={x:0,y:0};_179={xa:_178.x,xb:_178.x+document.body.clientWidth,ya:_178.y,yb:document.body.clientHeight};}else{_178=Utils.getCoords(_17d);_178.relX=DragUtil.getInitialLeft(_17d);_178.relY=DragUtil.getInitialTop(_17d);var pos=_17d.style.position?_17d.style.position:Utils.getCssStyle(_17d,"position");if(pos=="static"){_17a={x:0,y:0};}else{_17a=_178;}
_179={xa:_178.x,xb:_178.x+_17d.offsetWidth,ya:_178.y,yb:_178.y+_17d.offsetHeight};}}
_171=_el.offsetLeft-e.clientX;_172=_el.offsetTop-e.clientY;}
if(_17b){_177.style.width=[_el.offsetWidth,"px"].join("");_177.style.height=[_el.offsetHeight,"px"].join("");}
DragUtil.bringToFront(_16f);_177.style.zIndex=10000;document.onmouseup=mouseUp;document.onmousemove=mouseMove;document.body.focus();document.onselectstart=function(){return false;};return false;}
function construct(el,_18d,_18e,_18f,_190,_191){_el=el;_el.onmousedown=mouseDown;_el.style.cursor="default";_173=Utils.getZIndex(_el);_174=_18d;if(_174){_174.style.cursor="default";}else{_174=_el;}
_175=_el.style.position?_el.style.position:Utils.getCssStyle(_el,"position");if(_175!="absolute"&&_175!="fixed"){_el.style.position="relative";}
_177=document.createElement("div");if(_18f){_177.className=_18f;}
_177.style.position="absolute";_177.style.display="none";document.body.appendChild(_177);if(Utils.isBoolean(_191)){_17b=_191;}
if(Utils.isBoolean(_190)){_17c=_190;}
_17d=Utils.isNode(_18e)?_18e:_el.parentNode;_el.__drag=_16f;DragUtil.addDrag(_el,_16f);}
construct(el,_16a,_16b,_16c,_16d,_16e);}
var WidgetFactory={create:function(_192,_193,_194){if(Utils.isString(_192)){_192=document.createElement(_192);}
if(Utils.isNode(_192)){if(_193){_192.innerHTML=_193;}
return new SimpleWidget(_192,_194);}
return null;},createInput:function(type,_196){var _197=document.createElement("input");_197.setAttribute("type",type);return WidgetFactory.create(_197,null,_196);},createById:function(id){var node=document.getElementById(id);return Utils.isNode(node)?(Utils.isWidget(node.__wrapper)?node.__wrapper:new SimpleWidget(node)):null;}};function SimpleWidget(el,_19b){var _19c=this;this.__extends=Indexed;this.__extends();var _19d=null;var _19e=null;var _19f=new Array();var _1a0=null;this.setAttribute=function(name,_1a2){if(!_1a0){_1a0=new HashMap();}
_1a0.put(name,_1a2);};this.getAttribute=function(name){if(!_1a0){_1a0=new HashMap();}
return _1a0.get(name);};this.removeAttribute=function(name){if(!_1a0){_1a0=new HashMap();}
return _1a0.remove(name);};this.getAttributeMap=function(){return _1a0;};this.isSimple=function(){return true;};this.props={};this.setElement=function(el){if(!_19d&&Utils.isNode(el)){_19d=el;if(_19d.__wrapper){_19f=_19d.__wrapper.getStyles();_1a0=_19d.__wrapper.getAttributeMap();}
_19d.__wrapper=_19c;}};this.getElement=function(){return _19d;};this.setParent=function(p){if(_19e){_19e._a_removeChildElement(_19d);_19c._a_onDetach();}
if(Utils.isString(p)){p=document.getElementById(p);}
if(Utils.isNode(p)){_19e=Utils.isWidget(p.__wrapper)?p.__wrapper:new SimpleWidget(p);_19e._a_appendChildElement(_19d);_19c._a_onAttach();}else{if(Utils.isWidget(p)){_19e=p;_19e._a_appendChildElement(_19d);this._a_onAttach();}else{_19e=null;}}};this.getParent=function(){return _19e;};this.setId=function(id){_19d.id=id;};this.getId=function(){return _19d.id;};this.setName=function(name){_19d.name=name;};this.getName=function(){return _19d.name;};this.setTitle=function(_1a9){_19d.title=_1a9;};this.getTitle=function(){return _19d.title;};this.setStyle=function(_1aa){if(_1aa){if(_19f.length>0){_19f.splice(0,_19f.length);}
_19f.push(_1aa);_19d.className=_1aa;}};this.addStyle=function(_1ab){if(_1ab&&_19f.indexOf(_1ab)==-1){_19f.push(_1ab);_19d.className=_19f.length>1?_19f.join(" "):_19f[0];}};this.removeStyle=function(_1ac){var idx=_1ac?_19f.indexOf(_1ac):-1;if(idx!=-1){_19f.splice(idx,1);_19d.className=_19f.length>1?_19f.join(" "):_19f[0];return true;}
return false;};this.getStyle=function(){return _19d.className;};this.getStyles=function(){return _19f;};this.setStyleProperty=function(name,_1af){_19d.style[name]=_1af;};this.getStyleProperty=function(name){return _19d.style[name];};this.setElementProperty=function(name,_1b2){_19d[name]=_1b2;};this.getElementProperty=function(name){return _19d[name];};this.isAttached=function(){return _19e!=null;};this.addEventHandler=function(_1b4,_1b5){Utils.addHandlerToEvent(_1b5,_19d,_1b4);};this._a_appendChildElement=function(_1b6){_19d.appendChild(_1b6);};this._a_removeChildElement=function(_1b7){_19d.removeChild(_1b7);};this.setVisible=function(_1b8){_19d.style.display=_1b8?"":"none";};this.isVisible=function(){return _19d.style.display!="none";};this.toggle=function(){_19d.style.display=_19d.style.display=="none"?"":"none";};this._a_onAttach=function(){};this._a_onDetach=function(){};function construct(el,_1ba){if(Utils.isNode(el)){_19c.setElement(el);_19c.setStyle(_1ba);}}
construct(el,_19b);}
function AbstractWrapperWidget(){var _1bb=this;this.__extends=SimpleWidget;this.__extends();var _1bc=null;this.setChild=function(_1bd){if(Utils.isWidget(_1bd)&&!_1bb.equals(_1bd.getParent())){_1bc=_1bd;_1bc.setParent(_1bb);}};this.getChild=function(){return _1bc;};this.onlyChild=function(){return _1bc;};this.addChild=function(_1be){_1bb.setChild(_1be);};function construct(){}
construct();}
function AbstractContainerWidget(){var _1bf=this;this.__extends=SimpleWidget;this.__extends();var _1c0=new ArrayList();this.getChildren=function(){return _1c0;};this.size=function(){return _1c0.size();};this.getChild=function(_1c1){return _1c0.get(_1c1);};this.addChild=function(_1c2){if(Utils.isWidget(_1c2)&&!_1bf.equals(_1c2.getParent())){var _1c3=_1c0.size();_1c2=_1bf._a_filterAddCandidate(_1c2);if(_1c2){_1c0.add(_1c2);_1c2.setParent(_1bf);_1bf._a_onChildAdded(_1c2,_1c3);}}};this.removeChild=function(_1c4){var _1c5=_1c0.remove(_1c4);if(_1c5){_1c5.setParent(null);_1bf._a_onChildRemoved(_1c5,_1c4);}
return _1c5;};this.removeChildren=function(_1c6,_1c7){var size=_1c0.size();var end=_1c7?(_1c7>size?size:_1c7):size;var _1ca=_1c6?(_1c6<end?_1c6:end):0;for(var i=0,len=end-_1ca;i<len;i++){_1bf.removeChild(_1ca);}};this._a_filterAddCandidate=function(_1cd){return _1cd;};this._a_onChildAdded=function(_1ce,_1cf){};this._a_onChildRemoved=function(_1d0,_1d1){};function construct(){}
construct();}
function CustomWidget(){var _1d2=this;this.__extends=SimpleWidget;this.__extends();var _1d3=null;this.isSimple=function(){return false;};this.setWidget=function(_1d4){if(!_1d3&&Utils.isWidget(_1d4)){_1d3=_1d4;_1d2.setElement(_1d3.getElement());}};this.getWidget=function(){return _1d3;};this._a_onAttach=function(){_1d3.setParent(_1d2.getParent());};function construct(){}
construct();}
function SimplePanel(_1d5,_1d6){var _1d7=this;this.__extends=AbstractWrapperWidget;this.__extends();function construct(_1d8,_1d9){_1d7.setElement(document.createElement("div"));_1d7.setStyle(_1d9);_1d7.setChild(_1d8);}
construct(_1d5,_1d6);}
function SimpleCellPanel(_1da){var _1db=this;this.__extends=AbstractWrapperWidget;this.__extends();var _td=null;this._a_appendChildElement=function(_1dd){_td.appendChild(_1dd);};this._a_removeChildElement=function(_1de){_td.removeChild(_1de);};this.setBorder=function(_1df){_1db.setElementProperty("border",_1df);};this.setSpacing=function(_1e0){_1db.setElementProperty("cellSpacing",_1e0);};this.setPadding=function(_1e1){_1db.setElementProperty("cellPadding",_1e1);};function construct(_1e2){var _1e3=document.createElement("table");var _1e4=document.createElement("tbody");var tr=document.createElement("tr");_td=document.createElement("td");tr.appendChild(_td);_1e4.appendChild(tr);_1e3.appendChild(_1e4);_1db.setElement(_1e3);_1db.setElementProperty("cellPadding",0);_1db.setElementProperty("cellSpacing",0);_1db.setChild(_1e2);}
construct(_1da);}
function CenterPanel(_1e6,_1e7){var _1e8=this;this.__extends=AbstractWrapperWidget;this.__extends();function construct(_1e9,_1ea){_1e8.setElement(document.createElement("center"));_1e8.setStyle(_1ea);_1e8.setChild(_1e9);}
construct(_1e6,_1e7);}
function FlowPanel(_1eb){var _1ec=this;this.__extends=AbstractContainerWidget;this.__extends();function construct(_1ed){_1ec.setElement(document.createElement("div"));_1ec.setStyle(_1ed);}
construct(_1eb);}
function AbstractCellPanel(){var _1ee=this;this.__extends=AbstractContainerWidget;this.__extends();var _1ef=null;var _1f0={top:"vertical-align: top;",middle:"vertical-align: middle;",bottom:"vertical-align: bottom;"};var _1f1={left:"left",center:"center",right:"right"};this.getTBODY=function(){return _1ef;};this._a_filterAddCandidate=function(_1f2){var _1f3=new SimpleWidget(document.createElement("td"));_1f3.setElementProperty("align",_1f1["left"]);Utils.applyStyle(_1f3.getElement(),_1f0["top"]);_1f2.setParent(_1f3);return _1f3;};this._a_onChildAdded=function(_1f4,_1f5){_1f4.setIndex(_1f5);};this.setVerticalAlign=function(_1f6,_1f7){var al=_1f0[_1f7];if(al&&Utils.isWidget(_1f6)){var td=_1f6.getParent();if(td&&_1ee.equals(td.getParent())){Utils.applyStyle(td.getElement(),al);}}};this.setHorizontalAlign=function(_1fa,_1fb){var al=_1f1[_1fb];if(al&&Utils.isWidget(_1fa)){var td=_1fa.getParent();if(td&&_1ee.equals(td.getParent())){td.setElementProperty("align",al);}}};this.setCellWidth=function(_1fe,_1ff){if(Utils.isWidget(_1fe)){var td=_1fe.getParent();if(td&&_1ee.equals(td.getParent())){td.setElementProperty("width",_1ff);}}};this.setCellHeight=function(_201,_202){if(Utils.isWidget(_201)){var td=_201.getParent();if(td&&_1ee.equals(td.getParent())){td.setElementProperty("height",_202);}}};this.setBorder=function(_204){_1ee.setElementProperty("border",_204);};this.setSpacing=function(_205){_1ee.setElementProperty("cellSpacing",_205);};this.setPadding=function(_206){_1ee.setElementProperty("cellPadding",_206);};function construct(){_1ef=document.createElement("tbody");var _207=document.createElement("table");_207.appendChild(_1ef);_1ee.setElement(_207);}
construct();}
function VerticalCellPanel(){var _208=this;this.__extends=AbstractCellPanel;this.__extends();this._a_appendChildElement=function(_209){var tr=document.createElement("tr");tr.appendChild(_209);_208.getTBODY().appendChild(tr);};this._a_removeChildElement=function(_20b){var tr=_20b.parentNode;tr.removeChild(_20b);_208.getTBODY().removeChild(tr);};function construct(){_208.setElementProperty("cellSpacing",0);_208.setElementProperty("cellPadding",0);}
construct();}
function HorizontalCellPanel(){var _20d=this;this.__extends=AbstractCellPanel;this.__extends();var _tr=null;this.getTR=function(){return _tr;};this._a_appendChildElement=function(_20f){_tr.appendChild(_20f);};this._a_removeChildElement=function(_210){_tr.removeChild(_210);};function construct(){_20d.setElementProperty("cellSpacing",0);_20d.setElementProperty("cellPadding",0);_tr=document.createElement("tr");_20d.getTBODY().appendChild(_tr);}
construct();}
function DeckPanel(){var _211=this;this.__extends=AbstractContainerWidget;this.__extends();var _212=null;function styleChild(_213,_214,_215){_213.setStyleProperty("display",_214);}
this._a_onChildAdded=function(_216,_217){styleChild(_216,"none","100%");};this._a_onChildRemoved=function(_218,_219){styleChild(_218,"","");};this.show=function(_21a){var _21b=_211.getChild(_21a);if(_21b){if(_212){_212.setStyleProperty("display","none");}
_212=_21b;_212.setStyleProperty("display","");}else{if(_212){_212.setStyleProperty("display","none");_212=null;}}};this.getCurrentWidget=function(){return _212;};function construct(){_211.setElement(document.createElement("div"));}
construct();}
function AbstractListPanel(){var _21c=this;this.__extends=AbstractContainerWidget;this.__extends();this._a_filterAddCandidate=function(_21d){var li=new SimpleWidget(document.createElement("li"));_21d.setParent(li);return li;};function construct(){_21c.setElement(document.createElement("ul"));Utils.applyStyle(_21c.getElement(),"margin:0; padding:0; list-style:none;");}
construct();}
function VerticalListPanel(){var _21f=this;this.__extends=AbstractListPanel;this.__extends();this._a_onChildAdded=function(_220,_221){_220.setIndex(_221);};function construct(){}
construct();}
function HorizontalListPanel(){var _222=this;this.__extends=AbstractListPanel;this.__extends();this._a_onChildAdded=function(_223,_224){_223.setIndex(_224);_223.setStyleProperty("display","inline");_223.getElement().firstChild.style.display="inline";};this._a_onChildRemoved=function(_225,_226){_225.setStyleProperty("display","");_225.getElement().firstChild.style.display="";};function construct(){}
construct();}
function PopupPanel(_227){var _228=this;this.__extends=AbstractContainerWidget;this.__extends();this.center=function(){Utils.positionCenter(_228.getElement());};this.setPosition=function(left,top){var x=Utils.isNumber(left)?[left,"px"].join(""):left;var y=Utils.isNumber(top)?[top,"px"].join(""):top;_228.setStyleProperty("left",x);_228.setStyleProperty("top",y);};this.show=function(){_228.setVisible(true);};this.isHidden=function(){return!_228.isVisible();};this.hide=function(){_228.setVisible(false);};function construct(_22d){var div=document.createElement("div");_228.setElement(div);_228.setVisible(false);_228.setStyle(_22d);_228.setStyleProperty("position","absolute");}
construct(_227);}
function SimpleTable(rows,cols,_231){var _232=this;this.__extends=SimpleWidget;this.__extends();var _233={top:"vertical-align: top;",middle:"vertical-align: middle;",bottom:"vertical-align: bottom;"};var _234={left:"left",center:"center",right:"right"};var _235=null;var _236=null;this.setWidget=function(row,col,_239){if(_235>row&&_236>col){var cell=_232.getElement().rows[row].cells[col];Utils.refreshElement(cell);if(Utils.isWidget(_239)){cell.appendChild(_239.getElement());}}};this.getWidget=function(row,col){if(_235>row&&_236>col){var _23d=_232.getElement().rows[row].cells[col].firstChild;return _23d&&Utils.isWidget(_23d.__wrapper)?_23d.__wrapper:null;}
return null;};this.setRowStyle=function(row,_23f){if(_235>row){_232.getElement().rows[row].className=_23f;}};this.setCellStyle=function(row,col,_242){if(_235>row&&_236>col){_232.getElement().rows[row].cells[col].className=_242;}};this.styleOddEvenRows=function(_243,_244,_245,_246){var end=_246?(_246>_235?_235:_246):_235;var _248=_245?(_245<end?_245:end):0;for(var i=0,len=end-_248;i<len;i++,_248++){_232.getElement().rows[_248].className=_248%2==0?_244:_243;}};this.addRow=function(){var tr=_232.getElement().insertRow(_235);for(var j=0;j<_236;j++){tr.insertCell(j);}
return _235++;};this.insertRow=function(row){if(row<_235){var tr=_232.getElement().insertRow(row);for(var j=0;j<_236;j++){tr.insertCell(j);}
return _235++;}
return _235;};this.removeRow=function(row){if(row<_235){_232.getElement().deleteRow(row);_235--;return true;}
return false;};this.removeRows=function(_251,_252){var end=_252?(_252>_235?_235:_252):_235;var _254=_251?(_251<end?_251:end):0;for(var i=0,len=end-_254;i<len;i++,_235--){_232.getElement().deleteRow(_254);}};this.getTD=function(row,col){return _235>row&&_236>col?_232.getElement().rows[row].cells[col]:null;};this.getTR=function(row){return _235>row?_232.getElement().rows[row]:null;};this.getRowCount=function(){return _235;};this.setBorder=function(_25a){_232.setElementProperty("border",_25a);};this.setSpacing=function(_25b){_232.setElementProperty("cellSpacing",_25b);};this.setPadding=function(_25c){_232.setElementProperty("cellPadding",_25c);};this.setVerticalAlign=function(row,col,_25f){var al=_233[_25f];var td=_232.getTD(row,col);if(al&&td){Utils.applyStyle(td,al);}};this.setHorizontalAlign=function(row,col,_264){var al=_234[_264];var td=_232.getTD(row,col);if(al&&td){td["align"]=al;}};this.setCellWidth=function(row,col,_269){var td=_232.getTD(row,col);if(td){td["width"]=_269;}};this.setCellHeight=function(row,col,_26d){var td=_232.getTD(row,col);if(td){td["height"]=_26d;}};function construct(rows,cols,_271){var _272=document.createElement("table");_235=rows||0;_236=cols||0;for(var i=0;i<_235;i++){var tr=_272.insertRow(i);for(var j=0;j<cols;j++){tr.insertCell(j);}}
_232.setElement(_272);_232.setStyle(_271);_232.setElementProperty("cellSpacing",0);_232.setElementProperty("cellPadding",0);}
construct(rows,cols,_231);}
function Hyperlink(_276,_277,_278){var _279=this;this.__extends=SimpleWidget;this.__extends();function construct(_27a,_27b,_27c){var a=document.createElement("a");if(Utils.isString(_27a)){a.innerHTML=_27a;}else{if(Utils.isNode(_27a)){a.appendChild(_27a);}else{if(Utils.isWidget(_27a)){a.appendChild(_27a.getElement());}}}
a.href=["#",_27b].join("");_279.setElement(a);_279.setStyle(_27c);}
construct(_276,_277,_278);}
function SelectBox(_27e){var _27f=this;this.__extends=SimpleWidget;this.__extends();var _280="";var _281=new Array();var _282=this.setElementProperty;this.setElementProperty=function(name,_284){if(name!="value"){_282(name,_284);return;}
_27f.getElement().selectedIndex=0;};var _285=this.getElementProperty;this.getElementProperty=function(name){return name!="value"?_285(name):_27f.getValue();};var _287=this.addEventHandler;this.addEventHandler=function(_288,_289){if(_288!="onchange"){_287(_288,_289);return;}
_281.push(_289);};this.getValue=function(){if(_27f.size()>0){var sel=_27f.getElement();_280=sel.options[sel.selectedIndex].value;}else{_280="";}
return _280;};this.size=function(){return _27f.getElement().options.length;};this.addEntry=function(_28b,_28c){var _28d=document.createElement("option");_28d.value=_28b;_28d.innerHTML=_28c;_27f.getElement().appendChild(_28d);};this.removeEntry=function(idx){if(idx<_27f.getElement().options.length){_27f.getElement().remove(idx);return true;}
return false;};this.removeEntries=function(_28f,_290){var size=_27f.size();var end=_290?(_290>_rows?size:_290):size;var _293=_28f?(_28f<end?_28f:end):0;for(var i=0,len=end-_293;i<len;i++){_27f.getElement().remove(_293);}};function onChange(e){var sel=_27f.getElement();_280=sel.options[sel.selectedIndex].value;for(var i in _281){_281[i](e,_280);}}
function construct(_299){var _29a=document.createElement("select");Utils.addHandlerToEvent(onChange,_29a,"onchange");_27f.setElement(_29a);if(_299){_27f.addEntry("","");}}
construct(_27e);}
function AbstractPane(){var _29b=this;this.__extends=FlowPanel;this.__extends();var _29c=null;var _29d=null;var _29e=null;var _29f="/";this.linkHidden=false;this.getPanel=function(){return _29b;};this.setName=function(name){_29c=name;};this.getName=function(){return _29c;};this.setDelim=function(_2a1){_29f=_2a1;};this.getDelim=function(){return _29f;};this.setParentPane=function(_2a2){if(_2a2&&_2a2.getCompositeToken){_29d=_2a2;_29b._a_onParentPaneSet();}};this.getParentPane=function(){return _29d;};this.isRootPane=function(){return _29d==null;};this._a_onParentPaneSet=function(){};this.getDepth=function(){return _29d?_29d.getDepth()+1:0;};this.setToken=function(_2a3){_29e=_2a3;};this.getToken=function(){return _29e;};this.getCompositeToken=function(_2a4){if(_2a4){return _29d?[_29d.getCompositeToken(_29e),_29f,_2a4].join(""):[_29e,_2a4].join(_29f);}
return _29d?_29d.getCompositeToken(_29e):_29e;};this.activate=function(_2a5){};this.passivate=function(_2a6){};this.init=function(){};this.reset=function(){};function construct(){}
construct();}
function AbstractTreePane(){var _2a7=this;this.__extends=AbstractPane;this.__extends();var _2a8=null;var _2a9=new IndexedMap();var _2aa=true;var _2ab=true;this.setIndented=function(_2ac){_2ab=_2ac;};this.isIndented=function(){return _2ab;};this.isExpanded=function(){return _2aa;};function expandOrCollapse(_2ad,_2ae){for(var i=0;i<_2ad.length;i++){var p=_2ad[i];p.setVisible(_2ae);if(p.props.panes){expandOrCollapse(p.props.panes,_2ae);}}}
this.collapsePanes=function(){_2aa=false;expandOrCollapse(_2a7.props.panes,_2aa);};this.expandPanes=function(){_2aa=true;expandOrCollapse(_2a7.props.panes,_2aa);};this.toggleTree=function(){_2aa=!_2aa;expandOrCollapse(_2a7.props.panes,_2aa);};this.setDefaultLinkStyle=function(_2b1){_2a8=_2b1;};this.getDefaultLinkStyle=function(){if(!_2a8){var _2b2=_2a7.getParentPane();_2a8=_2b2?_2b2.getDefaultLinkStyle():null;}
return _2a8;};this.newLink=function(_2b3,_2b4){return WidgetFactory.create("a",_2b3,_2b4);};this.newPane=function(_2b5){return new FlowPanel(_2b5);};this.newEntryPane=function(_2b6,p,_2b8){return _2b8?_2a7.addEntry(WidgetFactory.create("a",_2b6,_2b8.k),new FlowPanel(_2b8.v),p):_2a7.addEntry(_2b6,new FlowPanel(),p);};this.addTreePane=function(pane){this.addEntry(pane.getName(),pane);};this.addEntry=function(_2ba,pane,p){var link=Utils.isString(_2ba)?_2a7.newLink(_2ba):_2ba;var _2be=Utils.isWidget(p)?(p.props.tree==_2a7?p:_2a7):_2a7;if(_2ab){pane.setStyleProperty("margin","2px 0 2px 10px");}
link.addEventHandler("onclick",function(e){pane.toggle();});_2be.addChild(new SimplePanel(link));_2be.addChild(pane);if(pane.getDepth){pane.setParentPane(_2be);if(_2a7.equals(_2be)){_2a9.put(pane.getToken(),pane);}}
link.addStyle(_2a7.getDefaultLinkStyle());pane.props.tree=_2a7;if(!_2be.props.panes){_2be.props.panes=new Array();}
_2be.props.panes.push(pane);return pane;};this.init=function(){if(_2a7.isRootPane()){_2a7.collapsePanes(_2a7.props.panes);}
var map=_2a9.__wrappedGet();for(var i in map){map[i].init();}};this.activate=function(_2c2){_2a7.setVisible(true);var sub=_2a7.getDepth()+1;if(sub==_2c2.length){return;}
var pane=_2a9.get(_2c2[sub]);if(pane){pane.activate(_2c2);}};this.passivate=function(_2c5){};function construct(){_2a7.props.panes=new Array();}
construct();}