
var Utils={isBoolean:function(_1){return typeof _1=="boolean";},isNumber:function(_2){return typeof _2=="number";},isString:function(_3){return typeof _3=="string";},isArray:function(_4){return _4&&!Utils.isString(_4)?Utils.isNumber(_4.length):false;},isNode:function(_5){return _5&&_5.nodeName;},isWidget:function(_6){return _6&&_6.getElement;},isDraggable:function(el){return el&&el.__drag;},applyStyle:function(el,_9){if(document.all&&!window.opera){el.style.setAttribute("cssText",_9);}else{el.setAttribute("style",_9);}},getCssStyle:function(el,_b){if(el.currentStyle){return el.currentStyle[_b];}else{if(window.getComputedStyle){return window.getComputedStyle(el,"").getPropertyValue(_b);}}
return null;},getStyleProperty:function(el,_d){var p=el.style[_d];return p?p:Utils.getCssStyle(el,_d);},getZIndex:function(el){return el.style.zIndex?el.style.zIndex:(document.all?Utils.getCssStyle(el,"zIndex"):Utils.getCssStyle(el,"z-index"));},refreshElement:function(el){while(el.hasChildNodes()){el.removeChild(el.firstChild);}},trim:function(str){return str.replace(/^\s+/g,"").replace(/\s+$/g,"");},trimLineBreaks:function(str){return str.replace(/(\r\n|[\r\n])/g," ");},getParentName:function(el){var p=el.parentNode;if(!p){return null;}
var _15=p.name?p.name:p.getAttribute("name");return _15?_15:Utils.getParentName(p);},addHandlerToEvent:function(_16,el,ev){if(el.addEventListener){el.addEventListener(ev.substring(2),_16,false);}else{if(el.attachEvent){el.attachEvent(ev,_16);}else{var _19=el[ev];el[ev]=function(e){_19(e);_16(e);};}}},addOnLoad:function(_1b){var _1c=window.onload;window.onload=function(){if(typeof _1c=="function"){_1c();}
_1b();};},addOnUnload:function(_1d){var _1e=window.onunload;window.onunload=function(){if(typeof _1e=="function"){_1e();}
_1d();};},getEventSource:function(ev){if(!ev){ev=window.event;}
return ev.target?ev.target:ev.srcElement;},toggle:function(el){if(!el.style.display||el.style.display!="none"){el.style.display="none";}else{el.style.display="block";}},hideFirstChild:function(_21){if(_21&&_21.firstChild){_21.firstChild.style.display="none";}},hideLastChild:function(_22){if(_22&&_22.lastChild){_22.lastChild.style.display="none";}},getEventCoords:function(ev){var x=0;var y=0;if(document.all){x=document.documentElement.scrollLeft||document.body.scrollLeft;y=document.documentElement.scrollTop||document.body.scrollTop;x+=window.event.clientX;y+=window.event.clientY;}else{x=ev.pageX;y=ev.pageY;}
return{x:x,y:y};},getLeft:function(el){var _27=0;for(;;){if(!el.offsetParent){_27+=el.offsetLeft;break;}
_27+=(el.offsetLeft-el.scrollLeft);el=el.offsetParent;}
return _27;},getTop:function(el){var top=0;for(;;){if(!el.offsetParent){top+=el.offsetTop;break;}
top+=(el.offsetTop-el.scrollTop);el=el.offsetParent;}
return top;},getCoords:function(el){var _2b=0;var top=0;for(;;){if(!el.offsetParent){_2b+=el.offsetLeft;top+=el.offsetTop;break;}
_2b+=(el.offsetLeft-el.scrollLeft);top+=(el.offsetTop-el.scrollTop);el=el.offsetParent;}
return{x:_2b,y:top};},getCenterCoords:function(){var _2d=document.documentElement.scrollLeft||document.body.scrollLeft;var _2e=document.documentElement.scrollTop||document.body.scrollTop;var _2f=document.body.clientWidth/2+_2d;var top=document.body.clientHeight/2+_2e;return{x:_2f,y:top};},positionCenter:function(el){var _32=(document.body.clientWidth-el.offsetWidth)/2;var top=(document.body.clientHeight-el.offsetHeight)/2;var _34=document.documentElement.scrollLeft||document.body.scrollLeft;var _35=document.documentElement.scrollTop||document.body.scrollTop;el.style.left=[_34+_32,"px"].join("");el.style.top=[_35+top,"px"].join("");},newXHR:function(){return window.XMLHttpRequest?new XMLHttpRequest():new ActiveXObject("Microsoft.XMLHTTP");},_script_counter:0,findParentByNodeName:function(el,_37){return el.nodeName==_37?el:el.parentNode?Utils.findParentByNodeName(el.parentNode,_37):null;},deleteCookie:function(_38){document.cookie=[_38,"=","; expires=Thu, 01-Jan-70 00:00:01 GMT"].join("");},getCookie:function(_39){var c=document.cookie.split(";");for(var i=0;i<c.length;i++){var t=Utils.trim(c[i]);if(t.substring(0,_39.length)==_39){return t.substring(_39.length+1,t.length);}}
return null;},createCookie:function(_3d,_3e,_3f){var _40=Utils.isNumber(_3f)?new Date((1000*_3f)+new Date().getTime()).toGMTString():"";document.cookie=[_3d,"=",_3e,"; expires=",_40].join("");},validateForm:function(_41,_42,_43){if(_43){return Utils.validateFormResolveName(_41,_42);}
for(var i=0;i<_41.elements.length;i++){if(_41.elements[i].type.toLowerCase()=="text"){var _45=_41.elements[i];_45.value=Utils.trim(_45.value);if(_45.value.length<1){var msg=["Missing field: ",_45.name.substring(0,1).toUpperCase(),_45.name.substring(1)].join("");if(Utils.isNode(_42)){_42.innerHTML=msg;}else{alert(msg);}
_45.focus();return false;}}else{if(_41.elements[i].type.toLowerCase()=="textarea"){var ta=_41.elements[i];ta.value=Utils.trimLineBreaks(ta.value);ta.value=Utils.trim(ta.value);if(ta.value.length<1){var msg=["Missing field: ",ta.name.substring(0,1).toUpperCase(),ta.name.substring(1)].join("");if(Utils.isNode(_42)){_42.innerHTML=msg;}else{alert(msg);}
return false;}}else{if(_41.elements[i].nodeName.toLowerCase()=="select"){var sel=_41.elements[i];if(sel.value.length<1){var msg=["Missing value: ",sel.name.substring(0,1).toUpperCase(),sel.name.substring(1)].join("");if(Utils.isNode(_42)){_42.innerHTML=msg;}else{alert(msg);}
return false;}}else{if(_41.elements[i].type.toLowerCase()=="password"){var _49=_41.elements[i];var _4a=_49.value.length;var _4b=Utils.trim(_49.value).length;if(_4a==0){var msg=["Missing value: ",Utils.getParentName(_49)].join("");if(Utils.isNode(_42)){_42.innerHTML=msg;}else{alert(msg);}
_49.focus();_49.select();return false;}
if(_4a!=_4b){var msg="Your password must not contain any whitespace.";if(Utils.isNode(_42)){_42.innerHTML=msg;}else{alert(msg);}
_49.focus();_49.select();return false;}}}}}}
return true;},validateFormResolveName:function(_4c,_4d){for(var i=0;i<_4c.elements.length;i++){if(_4c.elements[i].type.toLowerCase()=="text"){var _4f=_4c.elements[i];_4f.value=Utils.trim(_4f.value);if(_4f.value.length<1){var msg=["Missing field: ",Utils.getParentName(_4f)].join("");if(Utils.isNode(_4d)){_4d.innerHTML=msg;}else{alert(msg);}
_4f.focus();return false;}}else{if(_4c.elements[i].type.toLowerCase()=="textarea"){var ta=_4c.elements[i];ta.value=Utils.trimLineBreaks(ta.value);ta.value=Utils.trim(ta.value);if(ta.value.length<1){var msg=["Missing field: ",Utils.getParentName(ta)].join("");if(Utils.isNode(_4d)){_4d.innerHTML=msg;}else{alert(msg);}
return false;}}else{if(_4c.elements[i].nodeName.toLowerCase()=="select"){var sel=_4c.elements[i];if(sel.value.length<1){var msg=["Missing value: ",Utils.getParentName(sel)].join("");if(Utils.isNode(_4d)){_4d.innerHTML=msg;}else{alert(msg);}
return false;}}else{if(_4c.elements[i].type.toLowerCase()=="password"){var _53=_4c.elements[i];var _54=_53.value.length;var _55=Utils.trim(_53.value).length;if(_54==0){var msg=["Missing value: ",Utils.getParentName(_53)].join("");if(Utils.isNode(_4d)){_4d.innerHTML=msg;}else{alert(msg);}
_53.focus();_53.select();return false;}
if(_54!=_55){var msg="Your password must not contain any whitespace.";if(Utils.isNode(_4d)){_4d.innerHTML=msg;}else{alert(msg);}
_53.focus();_53.select();return false;}}}}}}
return true;}};var History={handlers:new Array(),currentToken:window.location.hash,loopKey:null,back:function(){if(window.history.length){window.history.back();}},newItem:function(_56){if(_56!=History.currentToken){window.location.hash=_56;}},onHistoryChanged:function(_57){var h=History.handlers;for(var i in h){h[i](_57);}},getToken:function(){return History.currentToken;},addHandler:function(_5a){var idx=History.handlers.indexOf(_5a);if(idx==-1){History.handlers.push(_5a);}},loop:function(){var _5c=window.location.hash.substring(1);if(_5c!=History.currentToken){History.currentToken=_5c;History.onHistoryChanged(_5c);}},stop:function(){if(History.loopKey){window.clearInterval(History.loopKey);History.loopKey=null;}},isStarted:function(){return History.loopKey!=null;},start:function(){if(!History.loopKey){History.loopKey=window.setInterval(History.loop,250);}}};if(!Array.prototype.indexOf){Array.prototype.indexOf=function(elt){var len=this.length;var _5f=Number(arguments[1])||0;_5f=(_5f<0)?Math.ceil(_5f):Math.floor(_5f);if(_5f<0){_5f+=len;}
for(;_5f<len;_5f++){if(_5f in this&&this[_5f]===elt){return _5f;}}
return-1;};}
function JSObject(){var _60=this;this.equals=function(obj){return _60==obj;};function construct(){}
construct();}
function Indexed(){var _62=this;this.__extends=JSObject;this.__extends();var _63=-1;this.setIndex=function(_64){_63=_64;};this.getIndex=function(){return _63;};function construct(){}
construct();}
function AbstractCollection(){var _65=this;this.__extends=JSObject;this.__extends();this.isEmpty=function(){};this.clear=function(){};this.size=function(){};this.get=function(obj){};this.remove=function(obj){};function construct(){}
construct();}
function ArrayList(){var _68=this;this.__extends=AbstractCollection;this.__extends();var _69=new Array();this.add=function(obj){if(obj){var idx=_69.length;_69.push(obj);_68._a_onAdd(obj,idx,idx+1);}};this.remove=function(_6c){if(Utils.isNumber(_6c)){return _6c<_69.length?_69.splice(_6c,1)[0]:null;}else{if(_6c&&_6c.equals){for(var i in _69){if(_69[i].equals(_6c)){var _6e=_69.splice(i,1)[0];_68._a_onRemove(_6e,i,_69.length);return _6e;}}}}
return null;};this.get=function(_6f){return _6f<_69.length?_69[_6f]:null;};this.indexOf=function(obj){if(obj){for(var i in _69){if(_69[i].equals(obj)){return i;}}}
return-1;};this.contains=function(obj){return _68.indexOf(obj)!=-1;};this.size=function(){return _69.length;};this.clear=function(){_69.splice(0,_69.length);};this.isEmpty=function(){return _69.length==0;};this.__wrappedGet=function(){return _69;};this._a_onAdd=function(obj,_74,_75){};this._a_onRemove=function(obj,_77,_78){};function construct(){}
construct();}
function IndexedList(_79){var _7a=this;this.__extends=ArrayList;this.__extends();var _7b=Utils.isBoolean(_79)?_79:true;var _7c=this.add;this.add=function(obj){if(obj){if(!obj.setIndex){obj.setIndex=function(idx){obj.__index=idx;};obj.getIndex=function(){return obj.__index;};}
_7c(obj);}};this._a_onAdd=function(obj,_80,_81){obj.setIndex(_80);};function reflectRemoval(_82,_83){var _84=_7a.__wrappedGet();for(var i=_82;i<_83;i++){_84[i].setIndex(i);}}
this._a_onRemove=function(obj,_87,_88){if(_7b){reflectRemoval(_87,_88);}};function construct(){}
construct();}
function HashMap(){var _89=this;this.__extends=AbstractCollection;this.__extends();var _8a={};var _8b=0;this.put=function(key,_8d){if(key&&_8d){_8a[key]=_8d;_89._a_onPut(key,_8d,++_8b);}};this.get=function(key){return key?_8a[key]:null;};this.remove=function(key){if(key){var _90=_8a[key];_8a[key]=null;_89._a_onRemove(key,_90,--_8b);return _90;}
return null;};this.size=function(){return _8b;};this.clear=function(){_8a={};_8b=0;};this.isEmpty=function(){return _8b==0;};this.__wrappedGet=function(){return _8a;};this._a_onPut=function(key,_92,_93){};this._a_onRemove=function(key,_95,_96){};function construct(){}
construct();}
function IndexedMap(_97){var _98=this;this.__extends=HashMap;this.__extends();var _99=Utils.isBoolean(_97)?_97:true;var _9a=this.put;this.put=function(key,_9c){if(_9c){if(!_9c.setIndex){_9c.setIndex=function(idx){_9c.__index=idx;};_9c.getIndex=function(){return _9c.__index;};}
_9a(key,_9c);}};this._a_onPut=function(key,_9f,_a0){_9f.setIndex(_a0-1);};function reflectRemoval(_a1,_a2){var map=_98.__wrappedGet();var _a4=_a1.getIndex();for(var i in map){var v=map[i];if(v&&v.getIndex()>_a4){v.setIndex(v.getIndex()-1);}}}
this._a_onRemove=function(key,_a8,_a9){if(_99){reflectRemoval(_a8,_a9);}};function construct(){}
construct();}
function PooledRequest(pl){var _ab=this;this.__extends=JSObject;this.__extends();var _ac=pl;var _ad=Utils.newXHR();var _ae=null;this.handle=function(_af){var _b0=_ae;_ae=null;_ac.push(_ab);_b0(_af);};this.eval=function(_b1){_ab.handle(window.eval(["(",_b1,")"].join("")));};function handleDefault(){if(_ad.readyState==4){if(_ad.status==200){_ab.eval(_ad.responseText);}}}
this.sendCachable=function(url,_b3,_b4,_b5){_ae=_b4;_ad.open(_b5,url,true);_ad.onreadystatechange=handleDefault;_ad.send(null);};this.send=function(url,_b7,_b8,_b9){_ae=_b8;_ad.open(_b9,url,true);_ad.onreadystatechange=handleDefault;_ad.setRequestHeader("Content-Type","application/x-www-form-urlencoded");_ad.setRequestHeader("Content-Length",_b7.length);_ad.send(_b7);};this.doGet=function(url,_bb,_bc){_ab.sendCachable(url,_bb,_bc,"GET");};this.doDelete=function(url,_be,_bf){_ab.sendCachable(url,_be,_bf,"DELETE");};this.doPost=function(url,_c1,_c2){_ab.send(url,_c1,_c2,"POST");};this.doPut=function(url,_c4,_c5){_ab.send(url,_c4,_c5,"PUT");};this.getRequest=function(){return _ad;};function construct(){}
construct();}
function RequestPool(_c6){var _c7=this;this.__extends=JSObject;this.__extends();var _c8=new Array();this.push=function(req){_c8.push(req);};this.addNew=function(){_c8.push(new PooledRequest(_c7));};this.send=function(url,_cb,_cc){_c8.shift().send(url,_cb,_cc,"POST");};this.doPut=function(url,_ce,_cf){_c8.shift().doPut(url,_ce,_cf);};this.doPost=function(url,_d1,_d2){_c8.shift().doPost(url,_d1,_d2);};this.doGet=function(url,_d4,_d5){_c8.shift().doGet(url,_d4,_d5);};this.doDelete=function(url,_d7,_d8){_c8.shift().doDelete(url,_d7,_d8);};function construct(_d9){var len=_d9?_d9:4;for(var i=0;i<len;i++){_c8.push(new PooledRequest(_c7));}}
construct(_c6);}
function IFrameRequest(){var _dc=this;this.__extends=JSObject;this.__extends();var _dd=null;function scheduleRemove(){_dd.removeChild(_dd.firstChild);}
function cleanIFrameDiv(e,_df){var _e0=null;if(e.currentTarget){_e0=e.currentTarget.contentDocument.body.firstChild.innerHTML;}else{if(e.srcElement){_e0=e.srcElement.contentWindow.document.body.firstChild.innerHTML;}}
if(_df){_df(window.eval(["(",_e0,")"].join("")));}}
this.send=function(url,_e2,_e3){var _e4=url.indexOf("?")==-1?"?":"&";var ifr=document.createElement("iframe");Utils.addHandlerToEvent(function(e){cleanIFrameDiv(e,_e3);},ifr,"onload");Utils.applyStyle(ifr,"display:none");ifr.src=[url,_e4,_e2].join("");_dd.appendChild(ifr);};function construct(){_dd=document.createElement("div");Utils.applyStyle(_dd,"display:none");document.body.appendChild(_dd);}
construct();}
function ScriptRequest(){var _e7=this;this.__extends=JSObject;this.__extends();var _e8=null;var _e9=["scr",Utils._script_counter++].join("");var _ea=new Array();this.handle=function(_eb){var _ec=_ea.shift();if(_ec){_ec(_eb);}};this.send=function(url,_ee,_ef){var _f0=url.indexOf("?")==-1?["?callback=",_e9,".handle&"].join(""):["&callback=",_e9,".handle&"].join("");var scr=document.createElement("script");Utils.applyStyle(scr,"display:none");_ea.push(_ef);scr.src=[url,_f0,_ee].join("");_e8.appendChild(scr);};function construct(){window[_e9]=_e7;_e8=document.createElement("div");Utils.applyStyle(_e8,"display:none");document.body.appendChild(_e8);}
construct();}
function CometdClient(u,obj,_f4){var _f5=this;this.__extends=JSObject;this.__extends();var _f6=u.length-1==u.lastIndexOf("/")?u.substring(0,u.length-1):u;var _f7=obj;var _f8=null;var _f9={};var _fa=false;var _fb=false;var _fc=null;var _id=null;function handle(_fe){if(_fe){if(_fb){_f8.send(_f6,"action=reconnect",handle);}else{_fa=false;}
if(Utils.isArray(_fe)){for(var i in _fe){var m=_fe[i];var cb=_f9[m.channel];if(cb){if(_f7&&Utils.isString(cb)){_f7[cb](m);}else{cb(m);}}}}}}
function onConnect(c){_id=c.id;for(var i in c.channels){_f9[c.channels[i]]="tmp";}
_fa=true;if(Utils.isString(_fc)){_f7[_fc]();}else{if(_fc){_fc();}}
_f8.send(_f6,"action=reconnect",handle);}
this.isConnected=function(){return _fa;};this.getId=function(){return _id;};this.start=function(_104){if(!_fa){_fc=_104;_f8.send(_f6,"action=connect",onConnect);}
_fb=true;};this.stop=function(_105){if(_fa){_fa=false;_f8.send(_f6,"action=disconnect",_105?_105:function(){});}
_fb=false;};this.publish=function(_106,data){if(_fa){if(_106.lastIndexOf("/")==_106.length-1){_106=_106.substring(0,_106.length-1);}
var ch=_f9[_106];if(ch){_f8.send(_f6+_106+"?action=publish",data,handle);}}};this.subscribe=function(_109,_10a){if(_fa){if(_109.lastIndexOf("/")==_109.length-1){_109=_109.substring(0,_109.length-1);}
var old=_f9[_109];_f9[_109]=_10a;if(!old){_f8.send(_f6+_109,"action=subscribe",handle);}}};this.unsubscribe=function(_10c){if(_fa){if(_10c.lastIndexOf("/")==_10c.length-1){_10c=_10c.substring(0,_10c.length-1);}
var ch=_f9[_10c];if(ch){chanels[_10c]=null;_f8.send(_f6+_10c,"action=unsubscribe",handle);}}};function construct(u,obj,type){if(type){if(type=="iframe"){_f8=new IFrameRequest();}else{if(type=="script"){_f8=new ScriptRequest();}else{if(type=="xhr"){_f8=new RequestPool(5);}}}}
if(!_f8){_f8=new RequestPool(5);}}
construct(u,obj,_f4);}
var DragUtil={getInitialLeft:function(el){if(el.style.left){return parseInt(el.style.left);}
var left=Utils.getCssStyle(el,"left");var idx=left.indexOf("px");return idx==-1?0:parseInt(left.substring(0,idx));},getInitialTop:function(el){if(el.style.top){return parseInt(el.style.top);}
var top=Utils.getCssStyle(el,"top");var idx=top.indexOf("px");return idx==-1?0:parseInt(top.substring(0,idx));},_draggables:new HashMap(),_dropabbles:new HashMap(),addDrag:function(el,drag){DragUtil._draggables.put(el,drag);},addDragDrop:function(el,_11a){DragUtil._droppables.put(el,_11a);},_front:null,bringToFront:function(_11b){if(Utils.isNode(_11b)){_11b=_11b.__drag;}
if(_11b&&_11b.bringToFront){if(DragUtil._front){DragUtil._front.bringToBack();}
DragUtil._front=_11b;_11b.bringToFront();}}};function Draggable(el,_11d){var _11e=this;this.__extends=JSObject;this.__extends();var _el=null;var _120=0;var _121=0;var _122=null;var _123=null;var _124=null;var _125=null;this.getElement=function(){return _el;};this.bringToFront=function(){_el.style.zIndex=10000;};this.bringToBack=function(){_el.style.zIndex=_122;};this.reset=function(){if(_125){if(_124!="absolute"&&_124!="fixed"){_el.style.left=[_125.relX,"px"].join("");_el.style.top=[_125.relY,"px"].join("");}else{_el.style.left=[_125.initX,"px"].join("");_el.style.top=[_125.initY,"px"].join("");}}};function mouseMove(e){if(!e){e=window.event;}
_el.style.left=[_120+e.clientX,"px"].join("");_el.style.top=[_121+e.clientY,"px"].join("");}
function mouseUp(e){document.onmousemove=null;document.onselectstart=null;document.onmouseup=null;}
function mouseDown(e){if(!e){e=window.event;}
var el=e.target?e.target:e.srcElement;if(el!=_123){if(el==_el){DragUtil.bringToFront(_11e);}
return;}
if(_124!="absolute"&&_124!="fixed"){if(!_125){_125=Utils.getCoords(_el);_125.relX=DragUtil.getInitialLeft(_el);_125.relY=DragUtil.getInitialTop(_el);_120=_125.relX-e.clientX;_121=_125.relY-e.clientY;}else{var _12a=_el.style.left?parseInt(_el.style.left):0;var _12b=_el.style.top?parseInt(_el.style.top):0;_120=_12a-e.clientX;_121=_12b-e.clientY;}}else{if(!_125){_125=Utils.getCoords(_el);_125.initX=DragUtil.getInitialLeft(_el);_125.initY=DragUtil.getInitialTop(_el);}
_120=_el.offsetLeft-e.clientX;_121=_el.offsetTop-e.clientY;}
DragUtil.bringToFront(_11e);document.onmouseup=mouseUp;document.onmousemove=mouseMove;document.body.focus();document.onselectstart=function(){return false;};return false;}
function construct(el,_12d){_el=el;_el.onmousedown=mouseDown;_el.style.cursor="default";_122=Utils.getZIndex(_el);_123=_12d;if(_123){_123.style.cursor="default";}else{_123=_el;}
_124=_el.style.position?_el.style.position:Utils.getCssStyle(_el,"position");if(_124!="absolute"&&_124!="fixed"){_el.style.position="relative";}
_el.__drag=_11e;DragUtil.addDrag(_el,_11e);}
construct(el,_11d);}
function DraggableBounded(el,_12f,_130){var _131=this;this.__extends=JSObject;this.__extends();var _el=null;var _133=0;var _134=0;var _135=null;var _136=null;var _137=null;var _138=null;var _139=null;var _13a=null;var _13b=null;this.getElement=function(){return _el;};this.bringToFront=function(){_el.style.zIndex=10000;};this.bringToBack=function(){_el.style.zIndex=_135;};this.reset=function(){if(_138){if(_137!="absolute"&&_137!="fixed"){_el.style.left=[_138.relX,"px"].join("");_el.style.top=[_138.relY,"px"].join("");}else{_el.style.left=[_138.initX,"px"].join("");_el.style.top=[_138.initY,"px"].join("");}}};function mouseMove(e){if(!e){e=window.event;}
var x=_133+e.clientX+_138.x-_138.relX+_13b.x;var y=_134+e.clientY+_138.y-_138.relY+_13b.y;if(_13a.xa<x+1&&_13a.ya<y+1&&_13a.xb>x-1+_el.offsetWidth&&_13a.yb>y-1+_el.offsetHeight){_el.style.left=[_133+e.clientX,"px"].join("");_el.style.top=[_134+e.clientY,"px"].join("");}}
function mouseUp(e){document.onmousemove=null;document.onselectstart=null;document.onmouseup=null;}
function mouseDown(e){if(!e){e=window.event;}
var el=e.target?e.target:e.srcElement;if(el!=_136){if(el==_el){DragUtil.bringToFront(_131);}
return;}
if(_137!="absolute"&&_137!="fixed"){if(!_138){_13b={x:0,y:0};_138=Utils.getCoords(_el);_138.relX=DragUtil.getInitialLeft(_el);_138.relY=DragUtil.getInitialTop(_el);if(_139==document.body){_parentCoords={x:0,y:0,relX:0,relY:0};_13a={xa:_parentCoords.x,xb:_parentCoords.x+document.body.clientWidth,ya:_parentCoords.y,yb:document.body.clientHeight};}else{_parentCoords=Utils.getCoords(_139);_parentCoords.relX=0;_parentCoords.relY=0;_13a={xa:_parentCoords.x,xb:_parentCoords.x+_139.offsetWidth,ya:_parentCoords.y,yb:_parentCoords.y+_139.offsetHeight};}
_133=_138.relX-e.clientX;_134=_138.relY-e.clientY;}else{var _142=_el.style.left?parseInt(_el.style.left):0;var _143=_el.style.top?parseInt(_el.style.top):0;_133=_142-e.clientX;_134=_143-e.clientY;}}else{if(!_138){_138=Utils.getCoords(_el);_138.initX=DragUtil.getInitialLeft(_el);_138.initY=DragUtil.getInitialTop(_el);if(_139==document.body){_parentCoords={x:0,y:0,relX:0,relY:0};_13b={x:0,y:0};_13a={xa:_parentCoords.x,xb:_parentCoords.x+document.body.clientWidth,ya:_parentCoords.y,yb:document.body.clientHeight};}else{_parentCoords=Utils.getCoords(_139);_parentCoords.relX=DragUtil.getInitialLeft(_139);_parentCoords.relY=DragUtil.getInitialTop(_139);var pos=_139.style.position?_139.style.position:Utils.getCssStyle(_139,"position");if(pos=="static"){_13b={x:0,y:0};}else{_13b=_parentCoords;}
_13a={xa:_parentCoords.x,xb:_parentCoords.x+_139.offsetWidth,ya:_parentCoords.y,yb:_parentCoords.y+_139.offsetHeight};}}
_133=_el.offsetLeft-e.clientX;_134=_el.offsetTop-e.clientY;}
DragUtil.bringToFront(_131);document.onmouseup=mouseUp;document.onmousemove=mouseMove;document.body.focus();document.onselectstart=function(){return false;};return false;}
function construct(el,_146,_147){_el=el;_el.onmousedown=mouseDown;_el.style.cursor="default";_135=Utils.getZIndex(_el);_136=_146;if(_136){_136.style.cursor="default";}else{_136=_el;}
_137=_el.style.position?_el.style.position:Utils.getCssStyle(_el,"position");if(_137!="absolute"&&_137!="fixed"){_el.style.position="relative";}
_139=Utils.isNode(_147)?_147:_el.parentNode;_el.__drag=_131;DragUtil.addDrag(_el,_131);}
construct(el,_12f,_130);}
function DraggableProxy(el,_149,_14a,_14b,_14c){var _14d=this;this.__extends=JSObject;this.__extends();var _el=null;var _14f=0;var _150=0;var _151=null;var _152=null;var _153=null;var _154=null;var _155=null;var _156=true;var _157=true;this.getElement=function(){return _el;};this.bringToFront=function(){_el.style.zIndex=10000;};this.bringToBack=function(){_el.style.zIndex=_151;};this.setResizeProxy=function(_158){_156=_158;};this.isResizeProxy=function(){return _156;};this.setMoveOriginal=function(_159){_157=_159;};this.isMoveOriginal=function(){return _157;};this.reset=function(){if(_154){if(_153!="absolute"&&_153!="fixed"){_el.style.left=[_154.relX,"px"].join("");_el.style.top=[_154.relY,"px"].join("");}else{_el.style.left=[_154.initX,"px"].join("");_el.style.top=[_154.initY,"px"].join("");}}};function mouseMove(e){if(!e){e=window.event;}
_155.style.display="";_155.style.left=[_14f+e.clientX+_154.x-_154.relX,"px"].join("");_155.style.top=[_150+e.clientY+_154.y-_154.relY,"px"].join("");}
function mouseUp(e){document.onmousemove=null;document.onselectstart=null;document.onmouseup=null;if(_157){var x=parseInt(_155.style.left);var y=parseInt(_155.style.top);_el.style.left=[x-_154.x+_154.relX,"px"].join("");_el.style.top=[y-_154.y+_154.relY,"px"].join("");}
_155.style.zIndex=null;_155.style.display="none";}
function mouseDown(e){if(!e){e=window.event;}
var el=e.target?e.target:e.srcElement;if(el!=_152){if(el==_el){DragUtil.bringToFront(_14d);}
return;}
if(_153!="absolute"&&_153!="fixed"){if(!_154){_154=Utils.getCoords(_el);_154.relX=DragUtil.getInitialLeft(_el);_154.relY=DragUtil.getInitialTop(_el);_14f=_154.relX-e.clientX;_150=_154.relY-e.clientY;}else{var _160=_el.style.left?parseInt(_el.style.left):0;var _161=_el.style.top?parseInt(_el.style.top):0;_14f=_160-e.clientX;_150=_161-e.clientY;}}else{if(!_154){_154={x:0,y:0,relX:0,relY:0};_154.initX=DragUtil.getInitialLeft(_el);_154.initY=DragUtil.getInitialTop(_el);}
_14f=_el.offsetLeft-e.clientX;_150=_el.offsetTop-e.clientY;}
_151=_el.style.zIndex;if(_156){_155.style.width=[_el.offsetWidth,"px"].join("");_155.style.height=[_el.offsetHeight,"px"].join("");}
DragUtil.bringToFront(_14d);_155.style.zIndex=10000;document.onmouseup=mouseUp;document.onmousemove=mouseMove;document.body.focus();document.onselectstart=function(){return false;};return false;}
function construct(el,_163,_164,_165,_166){_el=el;_el.onmousedown=mouseDown;_el.style.cursor="default";_151=Utils.getZIndex(_el);_152=_163;if(_152){_152.style.cursor="default";}else{_152=_el;}
_153=_el.style.position?_el.style.position:Utils.getCssStyle(_el,"position");if(_153!="absolute"&&_153!="fixed"){_el.style.position="relative";}
_155=document.createElement("div");if(_164){_155.className=_164;}
_155.style.position="absolute";_155.style.display="none";document.body.appendChild(_155);if(Utils.isBoolean(_166)){_156=_166;}
if(Utils.isBoolean(_165)){_157=_165;}
_el.__drag=_14d;DragUtil.addDrag(_el,_14d);}
construct(el,_149,_14a,_14b,_14c);}
function DraggableProxyBounded(el,_168,_169,_16a,_16b,_16c){var _16d=this;this.__extends=JSObject;this.__extends();var _el=null;var _16f=0;var _170=0;var _171=null;var _172=null;var _173=null;var _174=null;var _175=null;var _176=null;var _177=null;var _178=null;var _179=true;var _17a=true;var _17b=null;this.getElement=function(){return _el;};this.bringToFront=function(){_el.style.zIndex=10000;};this.bringToBack=function(){_el.style.zIndex=_171;};this.setResizeProxy=function(_17c){_179=_17c;};this.isResizeProxy=function(){return _179;};this.setMoveOriginal=function(_17d){_17a=_17d;};this.isMoveOriginal=function(){return _17a;};this.setContainer=function(_17e){if(Utils.isNode(_17e)){_17b=_17e;}};this.getContainer=function(){return _17b;};this.reset=function(){if(_174){if(_173!="absolute"&&_173!="fixed"){_el.style.left=[_174.relX,"px"].join("");_el.style.top=[_174.relY,"px"].join("");}else{_el.style.left=[_174.initX,"px"].join("");_el.style.top=[_174.initY,"px"].join("");}}};function mouseMove(e){if(!e){e=window.event;}
_175.style.display="";var x=_16f+e.clientX+_174.x-_174.relX+_178.x;var y=_170+e.clientY+_174.y-_174.relY+_178.y;if(_177.xa<x+1&&_177.ya<y+1&&_177.xb>x-1+_el.offsetWidth&&_177.yb>y-1+_el.offsetHeight){_175.style.left=[x,"px"].join("");_175.style.top=[y,"px"].join("");}}
function mouseUp(e){document.onmousemove=null;document.onselectstart=null;document.onmouseup=null;if(_17a){var x=parseInt(_175.style.left);var y=parseInt(_175.style.top);_el.style.left=[x-_174.x+_174.relX-_178.x,"px"].join("");_el.style.top=[y-_174.y+_174.relY-_178.y,"px"].join("");}
_175.style.zIndex=null;_175.style.display="none";}
function mouseDown(e){if(!e){e=window.event;}
var el=e.target?e.target:e.srcElement;if(el!=_172){if(el==_el){DragUtil.bringToFront(_16d);}
return;}
if(_173!="absolute"&&_173!="fixed"){if(!_174){_178={x:0,y:0};_174=Utils.getCoords(_el);_174.relX=DragUtil.getInitialLeft(_el);_174.relY=DragUtil.getInitialTop(_el);if(_17b==document.body){_176={x:0,y:0,relX:0,relY:0};_177={xa:_176.x,xb:_176.x+document.body.clientWidth,ya:_176.y,yb:document.body.clientHeight};}else{_176=Utils.getCoords(_17b);_176.relX=0;_176.relY=0;_177={xa:_176.x,xb:_176.x+_17b.offsetWidth,ya:_176.y,yb:_176.y+_17b.offsetHeight};}
_16f=_174.relX-e.clientX;_170=_174.relY-e.clientY;}else{var _187=_el.style.left?parseInt(_el.style.left):0;var _188=_el.style.top?parseInt(_el.style.top):0;_16f=_187-e.clientX;_170=_188-e.clientY;}}else{if(!_174){_174={x:0,y:0,relX:0,relY:0};_174.initX=DragUtil.getInitialLeft(_el);_174.initY=DragUtil.getInitialTop(_el);if(_17b==document.body){_176={x:0,y:0,relX:0,relY:0};_178={x:0,y:0};_177={xa:_176.x,xb:_176.x+document.body.clientWidth,ya:_176.y,yb:document.body.clientHeight};}else{_176=Utils.getCoords(_17b);_176.relX=DragUtil.getInitialLeft(_17b);_176.relY=DragUtil.getInitialTop(_17b);var pos=_17b.style.position?_17b.style.position:Utils.getCssStyle(_17b,"position");if(pos=="static"){_178={x:0,y:0};}else{_178=_176;}
_177={xa:_176.x,xb:_176.x+_17b.offsetWidth,ya:_176.y,yb:_176.y+_17b.offsetHeight};}}
_16f=_el.offsetLeft-e.clientX;_170=_el.offsetTop-e.clientY;}
if(_179){_175.style.width=[_el.offsetWidth,"px"].join("");_175.style.height=[_el.offsetHeight,"px"].join("");}
DragUtil.bringToFront(_16d);_175.style.zIndex=10000;document.onmouseup=mouseUp;document.onmousemove=mouseMove;document.body.focus();document.onselectstart=function(){return false;};return false;}
function construct(el,_18b,_18c,_18d,_18e,_18f){_el=el;_el.onmousedown=mouseDown;_el.style.cursor="default";_171=Utils.getZIndex(_el);_172=_18b;if(_172){_172.style.cursor="default";}else{_172=_el;}
_173=_el.style.position?_el.style.position:Utils.getCssStyle(_el,"position");if(_173!="absolute"&&_173!="fixed"){_el.style.position="relative";}
_175=document.createElement("div");if(_18d){_175.className=_18d;}
_175.style.position="absolute";_175.style.display="none";document.body.appendChild(_175);if(Utils.isBoolean(_18f)){_179=_18f;}
if(Utils.isBoolean(_18e)){_17a=_18e;}
_17b=Utils.isNode(_18c)?_18c:_el.parentNode;_el.__drag=_16d;DragUtil.addDrag(_el,_16d);}
construct(el,_168,_169,_16a,_16b,_16c);}
var WidgetFactory={create:function(_190,_191,_192){if(Utils.isString(_190)){_190=document.createElement(_190);}
if(Utils.isNode(_190)){if(_191){_190.innerHTML=_191;}
return new SimpleWidget(_190,_192);}
return null;},createInput:function(type,_194){var _195=document.createElement("input");_195.setAttribute("type",type);return WidgetFactory.create(_195,null,_194);},createById:function(id){var node=document.getElementById(id);return Utils.isNode(node)?(Utils.isWidget(node.__wrapper)?node.__wrapper:new SimpleWidget(node)):null;}};function SimpleWidget(el,_199){var _19a=this;this.__extends=Indexed;this.__extends();var _19b=null;var _19c=null;var _19d=new Array();var _19e=null;this.setAttribute=function(name,_1a0){if(!_19e){_19e=new HashMap();}
_19e.put(name,_1a0);};this.getAttribute=function(name){if(!_19e){_19e=new HashMap();}
return _19e.get(name);};this.removeAttribute=function(name){if(!_19e){_19e=new HashMap();}
return _19e.remove(name);};this.getAttributeMap=function(){return _19e;};this.isSimple=function(){return true;};this.props={};this.setElement=function(el){if(!_19b&&Utils.isNode(el)){_19b=el;if(_19b.__wrapper){_19d=_19b.__wrapper.getStyles();_19e=_19b.__wrapper.getAttributeMap();}
_19b.__wrapper=_19a;}};this.getElement=function(){return _19b;};this.setParent=function(p){if(_19c){_19c._a_removeChildElement(_19b);_19a._a_onDetach();}
if(Utils.isString(p)){p=document.getElementById(p);}
if(Utils.isNode(p)){_19c=Utils.isWidget(p.__wrapper)?p.__wrapper:new SimpleWidget(p);_19c._a_appendChildElement(_19b);_19a._a_onAttach();}else{if(Utils.isWidget(p)){_19c=p;_19c._a_appendChildElement(_19b);this._a_onAttach();}else{_19c=null;}}};this.getParent=function(){return _19c;};this.setId=function(id){_19b.id=id;};this.getId=function(){return _19b.id;};this.setName=function(name){_19b.name=name;};this.getName=function(){return _19b.name;};this.setTitle=function(_1a7){_19b.title=_1a7;};this.getTitle=function(){return _19b.title;};this.setStyle=function(_1a8){if(_1a8){if(_19d.length>0){_19d.splice(0,_19d.length);}
_19d.push(_1a8);_19b.className=_1a8;}};this.addStyle=function(_1a9){if(_1a9&&_19d.indexOf(_1a9)==-1){_19d.push(_1a9);_19b.className=_19d.length>1?_19d.join(" "):_19d[0];}};this.removeStyle=function(_1aa){var idx=_1aa?_19d.indexOf(_1aa):-1;if(idx!=-1){_19d.splice(idx,1);_19b.className=_19d.length>1?_19d.join(" "):_19d[0];return true;}
return false;};this.getStyle=function(){return _19b.className;};this.getStyles=function(){return _19d;};this.setStyleProperty=function(name,_1ad){_19b.style[name]=_1ad;};this.getStyleProperty=function(name){return _19b.style[name];};this.setElementProperty=function(name,_1b0){_19b[name]=_1b0;};this.getElementProperty=function(name){return _19b[name];};this.isAttached=function(){return _19c!=null;};this.addEventHandler=function(_1b2,_1b3){Utils.addHandlerToEvent(_1b3,_19b,_1b2);};this._a_appendChildElement=function(_1b4){_19b.appendChild(_1b4);};this._a_removeChildElement=function(_1b5){_19b.removeChild(_1b5);};this.setVisible=function(_1b6){_19b.style.display=_1b6?"":"none";};this.isVisible=function(){return _19b.style.display!="none";};this.toggle=function(){_19b.style.display=_19b.style.display=="none"?"":"none";};this._a_onAttach=function(){};this._a_onDetach=function(){};function construct(el,_1b8){if(Utils.isNode(el)){_19a.setElement(el);_19a.setStyle(_1b8);}}
construct(el,_199);}
function AbstractWrapperWidget(){var _1b9=this;this.__extends=SimpleWidget;this.__extends();var _1ba=null;this.setChild=function(_1bb){if(Utils.isWidget(_1bb)&&!_1b9.equals(_1bb.getParent())){_1ba=_1bb;_1ba.setParent(_1b9);}};this.getChild=function(){return _1ba;};this.onlyChild=function(){return _1ba;};this.addChild=function(_1bc){_1b9.setChild(_1bc);};function construct(){}
construct();}
function AbstractContainerWidget(){var _1bd=this;this.__extends=SimpleWidget;this.__extends();var _1be=new ArrayList();this.getChildren=function(){return _1be;};this.size=function(){return _1be.size();};this.getChild=function(_1bf){return _1be.get(_1bf);};this.addChild=function(_1c0){if(Utils.isWidget(_1c0)&&!_1bd.equals(_1c0.getParent())){var _1c1=_1be.size();_1c0=_1bd._a_filterAddCandidate(_1c0);if(_1c0){_1be.add(_1c0);_1c0.setParent(_1bd);_1bd._a_onChildAdded(_1c0,_1c1);}}};this.removeChild=function(_1c2){var _1c3=_1be.remove(_1c2);if(_1c3){_1c3.setParent(null);_1bd._a_onChildRemoved(_1c3,_1c2);}
return _1c3;};this.removeChildren=function(_1c4,_1c5){var size=_1be.size();var end=_1c5?(_1c5>size?size:_1c5):size;var _1c8=_1c4?(_1c4<end?_1c4:end):0;for(var i=0,len=end-_1c8;i<len;i++){_1bd.removeChild(_1c8);}};this._a_filterAddCandidate=function(_1cb){return _1cb;};this._a_onChildAdded=function(_1cc,_1cd){};this._a_onChildRemoved=function(_1ce,_1cf){};function construct(){}
construct();}
function CustomWidget(){var _1d0=this;this.__extends=SimpleWidget;this.__extends();var _1d1=null;this.isSimple=function(){return false;};this.setWidget=function(_1d2){if(!_1d1&&Utils.isWidget(_1d2)){_1d1=_1d2;_1d0.setElement(_1d1.getElement());}};this.getWidget=function(){return _1d1;};this._a_onAttach=function(){_1d1.setParent(_1d0.getParent());};function construct(){}
construct();}
function SimplePanel(_1d3,_1d4){var _1d5=this;this.__extends=AbstractWrapperWidget;this.__extends();function construct(_1d6,_1d7){_1d5.setElement(document.createElement("div"));_1d5.setStyle(_1d7);_1d5.setChild(_1d6);}
construct(_1d3,_1d4);}
function SimpleCellPanel(_1d8){var _1d9=this;this.__extends=AbstractWrapperWidget;this.__extends();var _td=null;this._a_appendChildElement=function(_1db){_td.appendChild(_1db);};this._a_removeChildElement=function(_1dc){_td.removeChild(_1dc);};this.setBorder=function(_1dd){_1d9.setElementProperty("border",_1dd);};this.setSpacing=function(_1de){_1d9.setElementProperty("cellSpacing",_1de);};this.setPadding=function(_1df){_1d9.setElementProperty("cellPadding",_1df);};function construct(_1e0){var _1e1=document.createElement("table");var _1e2=document.createElement("tbody");var tr=document.createElement("tr");_td=document.createElement("td");tr.appendChild(_td);_1e2.appendChild(tr);_1e1.appendChild(_1e2);_1d9.setElement(_1e1);_1d9.setElementProperty("cellPadding",0);_1d9.setElementProperty("cellSpacing",0);_1d9.setChild(_1e0);}
construct(_1d8);}
function CenterPanel(_1e4,_1e5){var _1e6=this;this.__extends=AbstractWrapperWidget;this.__extends();function construct(_1e7,_1e8){_1e6.setElement(document.createElement("center"));_1e6.setStyle(_1e8);_1e6.setChild(_1e7);}
construct(_1e4,_1e5);}
function FlowPanel(_1e9){var _1ea=this;this.__extends=AbstractContainerWidget;this.__extends();function construct(_1eb){_1ea.setElement(document.createElement("div"));_1ea.setStyle(_1eb);}
construct(_1e9);}
function AbstractCellPanel(){var _1ec=this;this.__extends=AbstractContainerWidget;this.__extends();var _1ed=null;var _1ee={top:"vertical-align: top;",middle:"vertical-align: middle;",bottom:"vertical-align: bottom;"};var _1ef={left:"left",center:"center",right:"right"};this.getTBODY=function(){return _1ed;};this._a_filterAddCandidate=function(_1f0){var _1f1=new SimpleWidget(document.createElement("td"));_1f1.setElementProperty("align",_1ef["left"]);Utils.applyStyle(_1f1.getElement(),_1ee["top"]);_1f0.setParent(_1f1);return _1f1;};this._a_onChildAdded=function(_1f2,_1f3){_1f2.setIndex(_1f3);};this.setVerticalAlign=function(_1f4,_1f5){var al=_1ee[_1f5];if(al&&Utils.isWidget(_1f4)){var td=_1f4.getParent();if(td&&_1ec.equals(td.getParent())){Utils.applyStyle(td.getElement(),al);}}};this.setHorizontalAlign=function(_1f8,_1f9){var al=_1ef[_1f9];if(al&&Utils.isWidget(_1f8)){var td=_1f8.getParent();if(td&&_1ec.equals(td.getParent())){td.setElementProperty("align",al);}}};this.setCellWidth=function(_1fc,_1fd){if(Utils.isWidget(_1fc)){var td=_1fc.getParent();if(td&&_1ec.equals(td.getParent())){td.setElementProperty("width",_1fd);}}};this.setCellHeight=function(_1ff,_200){if(Utils.isWidget(_1ff)){var td=_1ff.getParent();if(td&&_1ec.equals(td.getParent())){td.setElementProperty("height",_200);}}};this.setBorder=function(_202){_1ec.setElementProperty("border",_202);};this.setSpacing=function(_203){_1ec.setElementProperty("cellSpacing",_203);};this.setPadding=function(_204){_1ec.setElementProperty("cellPadding",_204);};function construct(){_1ed=document.createElement("tbody");var _205=document.createElement("table");_205.appendChild(_1ed);_1ec.setElement(_205);}
construct();}
function VerticalCellPanel(){var _206=this;this.__extends=AbstractCellPanel;this.__extends();this._a_appendChildElement=function(_207){var tr=document.createElement("tr");tr.appendChild(_207);_206.getTBODY().appendChild(tr);};this._a_removeChildElement=function(_209){var tr=_209.parentNode;tr.removeChild(_209);_206.getTBODY().removeChild(tr);};function construct(){_206.setElementProperty("cellSpacing",0);_206.setElementProperty("cellPadding",0);}
construct();}
function HorizontalCellPanel(){var _20b=this;this.__extends=AbstractCellPanel;this.__extends();var _tr=null;this.getTR=function(){return _tr;};this._a_appendChildElement=function(_20d){_tr.appendChild(_20d);};this._a_removeChildElement=function(_20e){_tr.removeChild(_20e);};function construct(){_20b.setElementProperty("cellSpacing",0);_20b.setElementProperty("cellPadding",0);_tr=document.createElement("tr");_20b.getTBODY().appendChild(_tr);}
construct();}
function DeckPanel(){var _20f=this;this.__extends=AbstractContainerWidget;this.__extends();var _210=null;function styleChild(_211,_212,_213){_211.setStyleProperty("display",_212);}
this._a_onChildAdded=function(_214,_215){styleChild(_214,"none","100%");};this._a_onChildRemoved=function(_216,_217){styleChild(_216,"","");};this.show=function(_218){var _219=_20f.getChild(_218);if(_219){if(_210){_210.setStyleProperty("display","none");}
_210=_219;_210.setStyleProperty("display","");}else{if(_210){_210.setStyleProperty("display","none");_210=null;}}};this.getCurrentWidget=function(){return _210;};function construct(){_20f.setElement(document.createElement("div"));}
construct();}
function AbstractListPanel(){var _21a=this;this.__extends=AbstractContainerWidget;this.__extends();this._a_filterAddCandidate=function(_21b){var li=new SimpleWidget(document.createElement("li"));_21b.setParent(li);return li;};function construct(){_21a.setElement(document.createElement("ul"));Utils.applyStyle(_21a.getElement(),"margin:0; padding:0; list-style:none;");}
construct();}
function VerticalListPanel(){var _21d=this;this.__extends=AbstractListPanel;this.__extends();this._a_onChildAdded=function(_21e,_21f){_21e.setIndex(_21f);};function construct(){}
construct();}
function HorizontalListPanel(){var _220=this;this.__extends=AbstractListPanel;this.__extends();this._a_onChildAdded=function(_221,_222){_221.setIndex(_222);_221.setStyleProperty("display","inline");_221.getElement().firstChild.style.display="inline";};this._a_onChildRemoved=function(_223,_224){_223.setStyleProperty("display","");_223.getElement().firstChild.style.display="";};function construct(){}
construct();}
function PopupPanel(_225){var _226=this;this.__extends=AbstractContainerWidget;this.__extends();this.center=function(){Utils.positionCenter(_226.getElement());};this.setPosition=function(left,top){var x=Utils.isNumber(left)?[left,"px"].join(""):left;var y=Utils.isNumber(top)?[top,"px"].join(""):top;_226.setStyleProperty("left",x);_226.setStyleProperty("top",y);};this.show=function(){_226.setVisible(true);};this.isHidden=function(){return!_226.isVisible();};this.hide=function(){_226.setVisible(false);};function construct(_22b){var div=document.createElement("div");_226.setElement(div);_226.setVisible(false);_226.setStyle(_22b);_226.setStyleProperty("position","absolute");}
construct(_225);}
function SimpleTable(rows,cols,_22f){var _230=this;this.__extends=SimpleWidget;this.__extends();var _231={top:"vertical-align: top;",middle:"vertical-align: middle;",bottom:"vertical-align: bottom;"};var _232={left:"left",center:"center",right:"right"};var _233=null;var _234=null;this.setWidget=function(row,col,_237){if(_233>row&&_234>col){var cell=_230.getElement().rows[row].cells[col];Utils.refreshElement(cell);if(Utils.isWidget(_237)){cell.appendChild(_237.getElement());}}};this.getWidget=function(row,col){if(_233>row&&_234>col){var _23b=_230.getElement().rows[row].cells[col].firstChild;return _23b&&Utils.isWidget(_23b.__wrapper)?_23b.__wrapper:null;}
return null;};this.setRowStyle=function(row,_23d){if(_233>row){_230.getElement().rows[row].className=_23d;}};this.setCellStyle=function(row,col,_240){if(_233>row&&_234>col){_230.getElement().rows[row].cells[col].className=_240;}};this.styleOddEvenRows=function(_241,_242,_243,_244){var end=_244?(_244>_233?_233:_244):_233;var _246=_243?(_243<end?_243:end):0;for(var i=0,len=end-_246;i<len;i++,_246++){_230.getElement().rows[_246].className=_246%2==0?_242:_241;}};this.addRow=function(){var tr=_230.getElement().insertRow(_233);for(var j=0;j<_234;j++){tr.insertCell(j);}
return _233++;};this.insertRow=function(row){if(row<_233){var tr=_230.getElement().insertRow(row);for(var j=0;j<_234;j++){tr.insertCell(j);}
return _233++;}
return _233;};this.removeRow=function(row){if(row<_233){_230.getElement().deleteRow(row);_233--;return true;}
return false;};this.removeRows=function(_24f,_250){var end=_250?(_250>_233?_233:_250):_233;var _252=_24f?(_24f<end?_24f:end):0;for(var i=0,len=end-_252;i<len;i++,_233--){_230.getElement().deleteRow(_252);}};this.getTD=function(row,col){return _233>row&&_234>col?_230.getElement().rows[row].cells[col]:null;};this.getTR=function(row){return _233>row?_230.getElement().rows[row]:null;};this.getRowCount=function(){return _233;};this.setBorder=function(_258){_230.setElementProperty("border",_258);};this.setSpacing=function(_259){_230.setElementProperty("cellSpacing",_259);};this.setPadding=function(_25a){_230.setElementProperty("cellPadding",_25a);};this.setVerticalAlign=function(row,col,_25d){var al=_231[_25d];var td=_230.getTD(row,col);if(al&&td){Utils.applyStyle(td,al);}};this.setHorizontalAlign=function(row,col,_262){var al=_232[_262];var td=_230.getTD(row,col);if(al&&td){td["align"]=al;}};this.setCellWidth=function(row,col,_267){var td=_230.getTD(row,col);if(td){td["width"]=_267;}};this.setCellHeight=function(row,col,_26b){var td=_230.getTD(row,col);if(td){td["height"]=_26b;}};function construct(rows,cols,_26f){var _270=document.createElement("table");_233=rows||0;_234=cols||0;for(var i=0;i<_233;i++){var tr=_270.insertRow(i);for(var j=0;j<cols;j++){tr.insertCell(j);}}
_230.setElement(_270);_230.setStyle(_26f);_230.setElementProperty("cellSpacing",0);_230.setElementProperty("cellPadding",0);}
construct(rows,cols,_22f);}
function Hyperlink(_274,_275,_276){var _277=this;this.__extends=SimpleWidget;this.__extends();function construct(_278,_279,_27a){var a=document.createElement("a");if(Utils.isString(_278)){a.innerHTML=_278;}else{if(Utils.isNode(_278)){a.appendChild(_278);}else{if(Utils.isWidget(_278)){a.appendChild(_278.getElement());}}}
a.href=["#",_279].join("");_277.setElement(a);_277.setStyle(_27a);}
construct(_274,_275,_276);}
function SelectBox(_27c){var _27d=this;this.__extends=SimpleWidget;this.__extends();var _27e="";var _27f=new Array();var _280=this.setElementProperty;this.setElementProperty=function(name,_282){if(name!="value"){_280(name,_282);return;}
_27d.getElement().selectedIndex=0;};var _283=this.getElementProperty;this.getElementProperty=function(name){return name!="value"?_283(name):_27d.getValue();};var _285=this.addEventHandler;this.addEventHandler=function(_286,_287){if(_286!="onchange"){_285(_286,_287);return;}
_27f.push(_287);};this.getValue=function(){if(_27d.size()>0){var sel=_27d.getElement();_27e=sel.options[sel.selectedIndex].value;}else{_27e="";}
return _27e;};this.size=function(){return _27d.getElement().options.length;};this.addEntry=function(_289,_28a){var _28b=document.createElement("option");_28b.value=_289;_28b.innerHTML=_28a;_27d.getElement().appendChild(_28b);};this.removeEntry=function(idx){if(idx<_27d.getElement().options.length){_27d.getElement().remove(idx);return true;}
return false;};this.removeEntries=function(_28d,_28e){var size=_27d.size();var end=_28e?(_28e>_rows?size:_28e):size;var _291=_28d?(_28d<end?_28d:end):0;for(var i=0,len=end-_291;i<len;i++){_27d.getElement().remove(_291);}};function onChange(e){var sel=_27d.getElement();_27e=sel.options[sel.selectedIndex].value;for(var i in _27f){_27f[i](e,_27e);}}
function construct(_297){var _298=document.createElement("select");Utils.addHandlerToEvent(onChange,_298,"onchange");_27d.setElement(_298);if(_297){_27d.addEntry("","");}}
construct(_27c);}
function AbstractPane(){var _299=this;this.__extends=FlowPanel;this.__extends();var _29a=null;var _29b=null;var _29c=null;var _29d="/";this.linkHidden=false;this.getPanel=function(){return _299;};this.setName=function(name){_29a=name;};this.getName=function(){return _29a;};this.setDelim=function(_29f){_29d=_29f;};this.getDelim=function(){return _29d;};this.setParentPane=function(_2a0){if(_2a0&&_2a0.getCompositeToken){_29b=_2a0;_299._a_onParentPaneSet();}};this.getParentPane=function(){return _29b;};this.isRootPane=function(){return _29b==null;};this._a_onParentPaneSet=function(){};this.getDepth=function(){return _29b?_29b.getDepth()+1:0;};this.setToken=function(_2a1){_29c=_2a1;};this.getToken=function(){return _29c;};this.getCompositeToken=function(_2a2){if(_2a2){return _29b?[_29b.getCompositeToken(_29c),_29d,_2a2].join(""):[_29c,_2a2].join(_29d);}
return _29b?_29b.getCompositeToken(_29c):_29c;};this.activate=function(_2a3){};this.passivate=function(_2a4){};this.init=function(){};this.reset=function(){};function construct(){}
construct();}
function AbstractTreePane(){var _2a5=this;this.__extends=AbstractPane;this.__extends();var _2a6=null;var _2a7=new IndexedMap();var _2a8=true;var _2a9=true;this.setIndented=function(_2aa){_2a9=_2aa;};this.isIndented=function(){return _2a9;};this.isExpanded=function(){return _2a8;};function expandOrCollapse(_2ab,_2ac){for(var i=0;i<_2ab.length;i++){var p=_2ab[i];p.setVisible(_2ac);if(p.props.panes){expandOrCollapse(p.props.panes,_2ac);}}}
this.collapsePanes=function(){_2a8=false;expandOrCollapse(_2a5.props.panes,_2a8);};this.expandPanes=function(){_2a8=true;expandOrCollapse(_2a5.props.panes,_2a8);};this.toggleTree=function(){_2a8=!_2a8;expandOrCollapse(_2a5.props.panes,_2a8);};this.setDefaultLinkStyle=function(_2af){_2a6=_2af;};this.getDefaultLinkStyle=function(){if(!_2a6){var _2b0=_2a5.getParentPane();_2a6=_2b0?_2b0.getDefaultLinkStyle():null;}
return _2a6;};this.newLink=function(_2b1,_2b2){return WidgetFactory.create("a",_2b1,_2b2);};this.newPane=function(_2b3){return new FlowPanel(_2b3);};this.newEntryPane=function(_2b4,p,_2b6){return _2b6?_2a5.addEntry(WidgetFactory.create("a",_2b4,_2b6.k),new FlowPanel(_2b6.v),p):_2a5.addEntry(_2b4,new FlowPanel(),p);};this.addTreePane=function(pane){this.addEntry(pane.getName(),pane);};this.addEntry=function(_2b8,pane,p){var link=Utils.isString(_2b8)?_2a5.newLink(_2b8):_2b8;var _2bc=Utils.isWidget(p)?(p.props.tree==_2a5?p:_2a5):_2a5;if(_2a9){pane.setStyleProperty("margin","2px 0 2px 10px");}
link.addEventHandler("onclick",function(e){pane.toggle();});_2bc.addChild(new SimplePanel(link));_2bc.addChild(pane);if(pane.getDepth){pane.setParentPane(_2bc);if(_2a5.equals(_2bc)){_2a7.put(pane.getToken(),pane);}}
link.addStyle(_2a5.getDefaultLinkStyle());pane.props.tree=_2a5;if(!_2bc.props.panes){_2bc.props.panes=new Array();}
_2bc.props.panes.push(pane);return pane;};this.init=function(){if(_2a5.isRootPane()){_2a5.collapsePanes(_2a5.props.panes);}
var map=_2a7.__wrappedGet();for(var i in map){map[i].init();}};this.activate=function(_2c0){_2a5.setVisible(true);var sub=_2a5.getDepth()+1;if(sub==_2c0.length){return;}
var pane=_2a7.get(_2c0[sub]);if(pane){pane.activate(_2c0);}};this.passivate=function(_2c3){};function construct(){_2a5.props.panes=new Array();}
construct();}